export const claxedoRepositoryUrl = "https://github.com/kyashrathore/Claxedo"

export const cloudflareDeploymentPrompt = `Deploy the Claxedo user-deployed control plane to my Cloudflare account.

Start by getting the repository, then work from that checkout:

  git clone https://github.com/kyashrathore/Claxedo.git
  cd Claxedo
  bun install

Run bun install at the repository root before any Wrangler command, then always invoke Wrangler as "bunx wrangler", which prefers a workspace pin when one exists. Do NOT use "npx wrangler" — it ignores the workspace and always fetches an unpinned version.

THIS BUTTON SERVES THE USER-DEPLOYED PATH ONLY. The static product is one organization, multiplayer, Better Auth + D1 (CLAXEDO_ADAPTER_PROFILE='better-auth-d1'). It is the only hosted composition in this repository.

READ THE CANONICAL GUIDE FIRST — public-docs/user-deployed-cloudflare.md. It is generated by \`packages/claxedo-server/scripts/deploy/greenfield-user-deployed.ts\` and is the source of truth over anything written here. If this prompt and that guide disagree, stop and report the divergence instead of working around it.

PREREQUISITES. A Cloudflare account authenticated for Workers, D1, custom domains, and rate-limit bindings. Four unused D1 databases: separate auth and control-plane databases for production and staging (AUTH_DB and CONTROL_PLANE_DB bindings — they must be distinct). An OAuth client (GitHub by default; set CLAXEDO_AUTH_METHODS for google, github, and/or email-password).

THE RELEASE SEQUENCE. All commands run from packages/claxedo-server unless stated:

  export CLAXEDO_ADAPTER_PROFILE='better-auth-d1'
  bun run deploy:user-cloudflare:preflight
  bun run scripts/deploy/release-better-auth-d1.ts --deploy --bootstrap
  bun run scripts/deploy/release-better-auth-d1.ts
  bun run scripts/deploy/release-better-auth-d1.ts --deploy

Cutover and status come from the cutover operator:

  bun run scripts/deploy/cutover-better-auth-d1.ts --status
  bun run scripts/deploy/release-better-auth-d1.ts --cutover
  bun run scripts/deploy/release-better-auth-d1.ts --deploy --cutover

Greenfield proof comes first: bun run scripts/deploy/prove-greenfield-target-absence.ts writes .artifacts/deployments/greenfield-target-absence.json, and the cutover manifest SHAs (CLAXEDO_CUTOVER_TARGET_ABSENCE_SHA256, CLAXEDO_CUTOVER_DEPLOYMENT_MANIFEST_SHA256) are recorded before anything deploys.

VERIFY WITH REAL COMMANDS. After the Worker is up, curl its base URL and show me the raw output of each check. Prove auth fails closed with a garbage bearer (expect 401, never 200). A 200 on an unauthenticated probe is a launch-blocking misconfiguration — stop and report it.

HOW TO WORK WITH ME.
  Begin read-only. Inspect public-docs/user-deployed-cloudflare.md, the release scripts in packages/claxedo-server/scripts/deploy/, and the Better Auth + D1 composition in packages/claxedo-server/src/deployments/hosted-workerd/better-auth-d1-locked-worker.cf.ts.
  Give me a prerequisite table with four states: already configured, safe to generate, needs a decision from me, needs a secret from me.
  Ask for one missing decision or secret at a time. Never echo, log, commit, or place a secret in a command argument — use "wrangler secret put" over stdin.
  Name any resource that can create a bill before creating it, and wait for my approval.
  Deploy every unit from one reviewed git revision.
  Stop if a required path cannot be verified. Describe a partial deployment precisely rather than calling it complete.

Finish with the deployed URLs, the exact git revision, where every component runs, the raw verification output, unresolved or optional integrations, estimated recurring cost, upgrade instructions, and exact rollback and teardown commands.

Never weaken authentication, expose an unsigned service publicly, invent missing infrastructure, or bypass a failing security check.`
