export type WorkGraphServiceEnv = Readonly<{
  WORKGRAPH_DB: D1Database
  CLAXEDO_WORKGRAPH_ENVIRONMENT_ID: string
  CLAXEDO_WORKGRAPH_DEPLOYMENT_ID: string
  CLAXEDO_WORKGRAPH_SERVICE_BUILD_ID: string
  CLAXEDO_WORKGRAPH_BINDING_PROVENANCE: string
  CLAXEDO_WORKGRAPH_INITIAL_STATE: "installed_disabled"
}>
