import { readFileSync } from "node:fs"
import { codeExtensions, listFiles, parseArgs, styleExtensions } from "./lib/files"
import { lineAt, readSource, ts } from "./lib/parse"
import { finish, type Violation } from "./lib/report"
import { walk } from "./lib/tree"

const directives = [
  /^\/\/ ?@ts-expect-error$/,
  /^\/\/ ?(oxlint|eslint)-(disable|enable)(-next-line|-line)?( [\w@/-]+(, ?[\w@/-]+)*)?$/,
  /^\/\* ?(oxlint|eslint)-(disable|enable)(-next-line|-line)?( [\w@/-]+(, ?[\w@/-]+)*)? ?\*\/$/,
  /^\/\* ?@vite-ignore ?\*\/$/,
  /^\/\* ?[#@]__PURE__ ?\*\/$/,
  /^\/\/\/ ?<reference [^>]+\/>$/,
]
const generatedMarker = /^(\/\/|\/\*)\s*(@generated\b|generated by\b|auto-?generated\b|do not edit\b)/i

type Range = { readonly pos: number; readonly end: number }

function main(): never {
  const { root } = parseArgs(process.argv.slice(2))
  const codeFiles = listFiles(root, ["src", "e2e", "scripts"], codeExtensions)
  const styleFiles = listFiles(root, ["src"], styleExtensions)
  const violations: Violation[] = []
  for (const file of codeFiles) violations.push(...commentsInCode(file))
  for (const file of styleFiles) violations.push(...commentsInStyle(file))
  finish("no-comments", root, violations, codeFiles.length + styleFiles.length)
}

function commentsInCode(file: string): Violation[] {
  const { sf, text } = readSource(file)
  const jsxText = jsxTextRanges(sf)
  const violations: Violation[] = []
  const seen = new Set<number>()
  for (const range of commentRanges(sf, text)) {
    if (seen.has(range.pos) || jsxText.some((jsx) => range.pos >= jsx.pos && range.pos < jsx.end)) continue
    seen.add(range.pos)
    const verdict = judge(text.slice(range.pos, range.end), seen.size === 1)
    if (verdict) violations.push({ file, line: lineAt(sf, range.pos), message: verdict })
  }
  return violations
}

function commentRanges(sf: ts.SourceFile, text: string): Range[] {
  const ranges: Range[] = []
  const visit = (node: ts.Node): void => {
    ranges.push(...(ts.getLeadingCommentRanges(text, node.getFullStart()) ?? []))
    ranges.push(...(ts.getTrailingCommentRanges(text, node.getEnd()) ?? []))
    for (const child of node.getChildren(sf)) visit(child)
  }
  visit(sf)
  return ranges.sort((a, b) => a.pos - b.pos)
}

function jsxTextRanges(sf: ts.SourceFile): Range[] {
  const ranges: Range[] = []
  walk(sf, (node) => {
    if (ts.isJsxText(node)) ranges.push({ pos: node.pos, end: node.end })
  })
  return ranges
}

function judge(comment: string, first: boolean): string | undefined {
  const trimmed = comment.trim()
  if (directives.some((pattern) => pattern.test(trimmed))) return undefined
  if (first && generatedMarker.test(trimmed)) return undefined
  if (/^\/\/ ?@ts-ignore\b/.test(trimmed)) return "@ts-ignore hides the error; use a bare @ts-expect-error"
  if (/^\/\/ ?@ts-expect-error\b/.test(trimmed)) return "@ts-expect-error carries prose; the directive stands alone"
  return `comment is not a tool directive: ${preview(trimmed)}`
}

function preview(comment: string): string {
  const firstLine = comment.split("\n")[0] ?? ""
  return firstLine.length > 60 ? `${firstLine.slice(0, 57)}...` : firstLine
}

function commentsInStyle(file: string): Violation[] {
  const text = readFileSync(file, "utf8")
  const violations: Violation[] = []
  let quote: string | undefined
  let line = 1
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index]
    if (char === "\n") line += 1
    if (quote) {
      if (char === "\\") index += 1
      else if (char === quote) quote = undefined
    } else if (char === '"' || char === "'") {
      quote = char
    } else if (char === "/" && text[index + 1] === "*") {
      const close = text.indexOf("*/", index + 2)
      const end = close < 0 ? text.length : close + 2
      violations.push({ file, line, message: `comment is not a tool directive: ${preview(text.slice(index, end))}` })
      line += text.slice(index, end).split("\n").length - 1
      index = end - 1
    }
  }
  return violations
}

main()
