import { expect, test } from "bun:test"
import { check, type Rule, type Source } from "./check.ts"

const agents = `## Process-wide state

None, except these owners:
- \`src/transports/cursor-sdk/worker-registry.ts\`: the Cursor worker registry;
- \`src/transports/acp/pattern-validation.ts\`: ACP's validation pool.

## No comments
`
const budgets: Record<string, number> = {
  contract: 1200, translate: 550, rpc: 300, broker: 2300, registry: 900, capabilities: 450, profiles: 600,
  "transports/claude-sdk": 2100, "transports/codex-app-server": 2150,
  "transports/cursor-sdk": 1600, "transports/acp": 2950,
  "transports/pi-rpc": 650, "transports/opencode-sdk": 3000,
}

function inspect(path: string, text: string, options: { agents?: string; budgets?: Record<string, number> } = {}) {
  const sources: Source[] = [{ path, text }]
  return check(sources, options.agents ?? agents, options.budgets ?? budgets)
}

function passes(rule: Rule, path: string, text: string, options?: { agents?: string; budgets?: Record<string, number> }) {
  expect(inspect(path, text, options).filter(result => result.rule === rule)).toEqual([])
}

function fails(rule: Rule, path: string, text: string, expectedFix: RegExp, options?: { agents?: string; budgets?: Record<string, number> }) {
  const result = inspect(path, text, options).find(result => result.rule === rule)
  expect(result).toBeDefined()
  expect(result?.path).toBe(path)
  expect(result?.line).toBeGreaterThan(0)
  expect(result?.fix).toMatch(expectedFix)
}

test("no-comments accepts directives and rejects ordinary comments", () => {
  passes("no-comments", "src/contract/good.ts", "#!/usr/bin/env bun\n/// <reference types=\"bun\" />\n// @ts-expect-error reason\n// oxlint-disable-next-line no-console\n/* @vite-ignore */\n/*#__PURE__*/\n// @generated\nconst value = 1\n")
  fails("no-comments", "src/contract/bad.ts", "const x = 1 // explanation\n", /Remove the comment/)
  fails("no-comments", "src/contract/prose.ts", "// generated by hand from the spec\nconst x = 1\n", /Remove the comment/)
  fails("no-comments", "src/contract/prose.test.ts", "// explains the test\nconst x = 1\n", /Remove the comment/)
  passes("no-comments", "src/transports/codex-app-server/generated/types.ts", "// generated protocol\n")
  passes("no-comments", "src/transports/acp/url.ts", 'const url = `http://127.0.0.1:${port}/v1`\n')
  fails("no-comments", "src/transports/acp/template-comment.ts", 'const url = `http://${port /* explanation */}/v1`\n', /Remove the comment/)
})

test("size counts files and function bodies with the compiler AST", () => {
  passes("size", "src/contract/good.ts", "function small() {\n  return 1\n}\n")
  fails("size", "src/contract/large.ts", `const value = 1\n${"\n".repeat(300)}`, /Split the file/)
  fails("size", "src/contract/long.ts", `const f = () => {\n${"  void 0\n".repeat(40)}}\n`, /Split the function body/)
})

test("core-boundary enforces direction for relative imports and vendor SDKs", () => {
  passes("core-boundary", "src/broker/good.ts", 'import type { X } from "../contract/x"\n')
  fails("core-boundary", "src/broker/bad.ts", 'import type { X } from "../transports/acp/x"\n', /Move this dependency/)
  fails("core-boundary", "src/translate/vendor.ts", 'import "@openai/foo"\n', /Move this dependency/)
})

test("compose is the only production module outside transports that imports transports", () => {
  passes("compose-boundary", "src/compose.ts", 'import { AcpTransport } from "./transports/acp"\n')
  fails("compose-boundary", "src/registry/wrong.ts", 'import { AcpTransport } from "../transports/acp"\n', /Import transports only/)
  fails("compose-boundary", "src/host.ts", 'import { createHarnessComposer } from "./compose"\n', /package compose export/)
})

test("transport-boundary accepts only its own SDK and shared boundaries", () => {
  passes("transport-boundary", "src/transports/acp/good.ts", 'import "node:fs"\nimport "@agentclientprotocol/sdk"\nimport "../../contract/x"\nimport "../../translate/x"\nimport "../../profiles/claude/x"\nimport "@claxedo/agent-event-runtime"\n')
  fails("transport-boundary", "src/transports/acp/bad.ts", 'import "@cursor/sdk"\n', /Import only this transport/)
  fails("transport-boundary", "src/transports/pi-rpc/bad.ts", 'import "../../broker/x"\n', /Import only this transport/)
})

test("rpc is a shared transport mechanism without reverse dependencies", () => {
  passes("transport-boundary", "src/transports/pi-rpc/good.ts", 'import "../../rpc/channel"\n')
  fails("core-boundary", "src/rpc/bad.ts", 'import "../transports/pi-rpc/rpc"\n', /Move this dependency/)
})

test("no-policy-in-transports preserves types and protocol maps but rejects decisions", () => {
  passes("no-policy-in-transports", "src/transports/acp/good.ts", 'type Decision = "allow_once" | "deny"\nconst protocolDecisionMap = { yes: "allow_once", no: "deny" }\nconst naming = () => { if (title) return title }\n')
  fails("no-policy-in-transports", "src/transports/acp/bad.ts", 'const answer = "allow_always"\n', /Move the request decision/)
  fails("no-policy-in-transports", "src/transports/acp/goal.ts", "evaluateGoal()\n", /Move goal evaluation/)
  fails("no-policy-in-transports", "src/transports/acp/title.ts", "if (title) choose()\n", /Make title decisions/)
  passes("no-policy-in-transports", "src/transports/acp/projection.ts", "const projected = row.title === undefined ? {} : { title: row.title }\n")
  passes("no-policy-in-transports", "src/transports/acp/summary.ts", "const title = row.title; const projected = title === undefined ? {} : { title }\n")
})

test("process-wide-state reads named owners from AGENTS.md", () => {
  passes("process-wide-state", "src/contract/good.ts", "function make() { let local = new Map() }\n")
  fails("process-wide-state", "src/contract/bad.ts", "let count = 0\nconst cache = new Map()\n", /Move mutable state/)
  fails("process-wide-state", "src/contract/nested.ts", "const state = { cache: new WeakMap() }\n", /Move mutable state/)
  passes("process-wide-state", "src/transports/cursor-sdk/worker-registry.ts", "let workers = new Map()\n")
  fails("process-wide-state", "src/transports/cursor-sdk/worker-registry.ts", "let workers = new Map()\n", /Move mutable state/, { agents: "## Process-wide state\n\nNone.\n\n## No comments\n" })
  fails("process-wide-state", "src/transports/cursor-sdk/worker-registry.ts", "let workers = new Map()\n", /Move mutable state/, { agents: "## Process-wide state\n\n- the Cursor worker registry\n\n## No comments\n" })
  passes("process-wide-state", "src/contract/explicit.ts", "let value = 1\n", { agents: "## Process-wide state\n- `src/contract/explicit.ts`: reviewed owner\n\n## No comments\n" })
})

test("no-swallowed-errors catches empty handlers and error text comparisons", () => {
  passes("no-swallowed-errors", "src/contract/good.ts", "try { work() } catch (error) { throw error }\n")
  fails("no-swallowed-errors", "src/contract/catch.ts", "task.catch(async () => fallback())\n", /Handle and surface/)
  fails("no-swallowed-errors", "src/contract/empty.ts", "try { work() } catch (error) {}\n", /Handle or rethrow/)
  fails("no-swallowed-errors", "src/contract/message.ts", 'if (error.message.includes("oops")) handle()\n', /Match a typed error/)
  fails("no-swallowed-errors", "src/contract/short.ts", 'if (e.message.includes("oops")) handle()\n', /Match a typed error/)
  passes("no-swallowed-errors", "src/contract/input.ts", 'if (input.message === undefined) handle()\n')
  passes("no-swallowed-errors", "src/transports/acp/errors.ts", 'if (/oops/.test(error.message)) handle()\n')
})

test("no-polling rejects intervals and recursive timeouts", () => {
  passes("no-polling", "src/contract/good.ts", "setTimeout(() => finish(), 10)\n")
  fails("no-polling", "src/contract/interval.ts", "setInterval(tick, 10)\n", /Use an event/)
  fails("no-polling", "src/contract/loop.ts", "function poll() { setTimeout(() => poll(), 10) }\n", /self-rescheduling timeout/)
})

test("one-harness-table keeps harness dispatch in the registry", () => {
  passes("one-harness-table", "src/registry/harnesses.ts", 'const ids = ["claude", "codex", "cursor"]\nswitch (harnessId) { case "pi": break }\n')
  fails("one-harness-table", "src/contract/ids.ts", 'const ids = ["claude", "codex", "cursor"]\n', /Move the harness id table/)
  fails("one-harness-table", "src/contract/dispatch.ts", 'switch (transport.id) { case "acp": break }\n', /Move harness or transport id dispatch/)
})

test("budget reads per-part limits", () => {
  passes("budget", "src/contract/good.ts", "const value = 1\n", { budgets: { ...budgets, contract: 1 } })
  fails("budget", "src/contract/bad.ts", "const value = 1\nconst other = 2\n", /Reduce contract from 2 to 1/, { budgets: { ...budgets, contract: 1 } })
})

test("test code is held to the shared rules but not to production-only ones", () => {
  const long = `test("long", () => {\n${"  expect(1).toBe(1)\n".repeat(320)}})\n`
  passes("size", "src/contract/long.test.ts", long)
  passes("budget", "src/contract/long.test.ts", long, { budgets: { ...budgets, contract: 1 } })
  passes("transport-boundary", "src/transports/acp/session.test.ts", 'import { test } from "bun:test"\nimport "../../test-support/fake-services"\n')
  fails("transport-boundary", "src/transports/acp/session.ts", 'import { test } from "bun:test"\n', /Import only this transport/)
  passes("no-policy-in-transports", "src/transports/acp/session.test.ts", 'expect(answer).toEqual({ decision: "allow_once" })\n')
  passes("process-wide-state", "src/broker/requests.test.ts", "let broker = create()\n")
  fails("no-swallowed-errors", "src/broker/requests.test.ts", "task.catch(() => undefined)\n", /Handle and surface/)
  fails("one-harness-table", "src/broker/requests.test.ts", 'for (const id of ["claude", "codex", "cursor"]) run(id)\n', /Move the harness id table/)
})
