import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { SourceMapConsumer } from "/Users/yashvardhansingh/test/opencode/node_modules/.bun/source-map@0.7.6/node_modules/source-map/source-map.js";

const distAssets = "/Users/yashvardhansingh/test/opencode/packages/claxedo-app/dist/assets";
const jsFile = fs.readdirSync(distAssets).find((f) => /^main-.*\.js$/.test(f));
const jsPath = path.join(distAssets, jsFile);
const mapPath = jsPath + ".map";

const code = fs.readFileSync(jsPath);
const codeStr = code.toString("utf8");
const rawMap = JSON.parse(fs.readFileSync(mapPath, "utf8"));

// Build an array of line-start byte offsets in the generated file.
// Generated columns in source-map are UTF-16 code unit offsets within a line.
// We need byte offsets. Build per-line offset table mapping column->byte.
const lines = codeStr.split("\n");
// byteOffsetOfLineStart[i] = byte offset where line i (0-based, but sourcemap is 1-based) starts
const lineStartByte = new Array(lines.length);
{
  let acc = 0;
  for (let i = 0; i < lines.length; i++) {
    lineStartByte[i] = acc;
    acc += Buffer.byteLength(lines[i], "utf8") + 1; // +1 for \n
  }
}

// Given a 1-based line and 0-based column (UTF-16 units), return byte offset.
function genByteOffset(line1, col0) {
  const li = line1 - 1;
  if (li < 0 || li >= lines.length) return code.length;
  const lineStr = lines[li];
  // col0 is in UTF-16 units; slice and measure bytes
  const prefix = lineStr.slice(0, col0);
  return lineStartByte[li] + Buffer.byteLength(prefix, "utf8");
}

function bucketForSource(src) {
  if (!src) return "(no-source)";
  let s = src.replace(/^.*?node_modules\//, "node_modules/");
  // npm package bucket
  const nmIdx = s.indexOf("node_modules/");
  if (nmIdx >= 0) {
    const rest = s.slice(nmIdx + "node_modules/".length);
    const parts = rest.split("/");
    let pkg;
    if (parts[0].startsWith("@")) pkg = parts[0] + "/" + parts[1];
    else pkg = parts[0];
    // handle .bun/ vendored layout: .bun/pkg@ver/node_modules/realpkg
    if (pkg === ".bun" || pkg.startsWith(".bun")) {
      // find the LAST node_modules segment
      const lastNm = rest.lastIndexOf("node_modules/");
      if (lastNm >= 0) {
        const r2 = rest.slice(lastNm + "node_modules/".length).split("/");
        pkg = r2[0].startsWith("@") ? r2[0] + "/" + r2[1] : r2[0];
      }
    }
    return "npm:" + pkg;
  }
  // first-party: relative paths like ../../../ui/src/context/helper.tsx
  // or src/... (claxedo-app itself). Normalize away leading ../
  const norm = src.replace(/^(\.\.\/)+/, "");
  // norm examples: "ui/src/context/helper.tsx", "src/main.tsx", "app/src/..."
  const parts = norm.split("/");
  let pkg, areaParts;
  if (parts[0] === "ui" || parts[0] === "app") {
    pkg = parts[0];
    const srcIdx = parts.indexOf("src");
    areaParts = srcIdx >= 0 ? parts.slice(srcIdx + 1) : parts.slice(1);
  } else if (parts[0] === "src") {
    pkg = "claxedo-app";
    areaParts = parts.slice(1);
  } else {
    pkg = parts[0];
    areaParts = parts.slice(1);
  }
  // area = up to 2 segments
  const area = areaParts.slice(0, 2).join("/");
  return "fp:" + pkg + "/" + area;
}

const consumer = await new SourceMapConsumer(rawMap);

// Collect all mappings in generated order with a generated byte offset.
const mappings = [];
consumer.eachMapping((m) => {
  const off = genByteOffset(m.generatedLine, m.generatedColumn);
  mappings.push({ off, source: m.source });
}, null, SourceMapConsumer.GENERATED_ORDER);

// Sort by offset (eachMapping should already be ordered, but ensure)
mappings.sort((a, b) => a.off - b.off);

// Attribute byte spans: each mapping owns [off, nextOff)
const bucketBuffers = new Map(); // bucket -> array of Buffer slices
function addSpan(bucket, start, end) {
  if (end <= start) return;
  let arr = bucketBuffers.get(bucket);
  if (!arr) { arr = []; bucketBuffers.set(bucket, arr); }
  arr.push(code.subarray(start, end));
}

for (let i = 0; i < mappings.length; i++) {
  const cur = mappings[i];
  const next = i + 1 < mappings.length ? mappings[i + 1].off : code.length;
  const bucket = bucketForSource(cur.source);
  addSpan(bucket, cur.off, next);
}
// Bytes before first mapping
if (mappings.length && mappings[0].off > 0) {
  addSpan("(preamble)", 0, mappings[0].off);
}

consumer.destroy();

// Compute raw + gzip per bucket
const results = [];
let totalRaw = 0;
for (const [bucket, arr] of bucketBuffers) {
  const buf = Buffer.concat(arr);
  const gz = zlib.gzipSync(buf, { level: 9 });
  results.push({ bucket, raw: buf.length, gz: gz.length });
  totalRaw += buf.length;
}
results.sort((a, b) => b.gz - a.gz);

const wholeGz = zlib.gzipSync(code, { level: 9 }).length;

let npmGz = 0, fpGz = 0, otherGz = 0;
let npmRaw = 0, fpRaw = 0, otherRaw = 0;
for (const r of results) {
  if (r.bucket.startsWith("npm:")) { npmGz += r.gz; npmRaw += r.raw; }
  else if (r.bucket.startsWith("fp:")) { fpGz += r.gz; fpRaw += r.raw; }
  else { otherGz += r.gz; otherRaw += r.raw; }
}

const kb = (n) => (n / 1024).toFixed(1);
console.log("FILE:", jsFile);
console.log("Whole-chunk gzip:", kb(wholeGz), "KB  raw:", kb(code.length), "KB");
console.log("Attributed raw total:", kb(totalRaw), "KB");
console.log("");
console.log("SPLIT (sum-of-bucket-gzips, will exceed whole-chunk gzip):");
console.log("  npm   gz", kb(npmGz), "KB  raw", kb(npmRaw), "KB");
console.log("  fp    gz", kb(fpGz), "KB  raw", kb(fpRaw), "KB");
console.log("  other gz", kb(otherGz), "KB  raw", kb(otherRaw), "KB");
console.log("");
console.log("TOP 40 BUCKETS BY GZIP:");
console.log("rank  gzKB    rawKB   bucket");
results.slice(0, 40).forEach((r, i) => {
  console.log(
    String(i + 1).padStart(3) + "  " +
    kb(r.gz).padStart(7) + " " +
    kb(r.raw).padStart(7) + "   " +
    r.bucket
  );
});
