import { fileURLToPath } from "node:url"
import { acpScriptToken, expect, installedCli, SCRIPTED_ACP_HARNESS, sendPrompt, sessionRoute, test, UI } from "../harness"

const IMAGE = fileURLToPath(new URL("../../public/web-app-manifest-192x192.png", import.meta.url))
const IMAGE_NAME = "web-app-manifest-192x192.png"

test("06 composer: a marked image, an @file pill and a slash command popover all reach the sent prompt", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("composer")
  await stack.acp.write("ack", { steps: [{ kind: "text", text: "Received the attachments" }] })
  const session = await api.createSession(workspace.directory, { title: "Composer", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const prompt = app.getByRole("textbox", { name: UI.composer })
  await expect(app.getByRole("button", { name: UI.sendIdle })).toBeVisible()

  await prompt.click()
  await app.keyboard.type("/")
  await expect(app.getByRole("listbox", { name: "Commands" })).toBeVisible()
  await app.keyboard.press("Escape")
  await expect(app.getByRole("listbox", { name: "Commands" })).toHaveCount(0)
  await app.keyboard.press("Backspace")

  const chooser = app.waitForEvent("filechooser")
  await app.getByRole("button", { name: "Add", exact: true }).click()
  await app.getByRole("menuitem", { name: /Images and files/ }).click()
  await (await chooser).setFiles(IMAGE)
  await app.getByRole("button", { name: "Mark up image" }).click()
  const dialog = app.getByRole("dialog", { name: "Mark up image" })
  const picture = await dialog.getByRole("img", { name: IMAGE_NAME }).boundingBox()
  if (!picture) throw new Error("The image to mark has no box")
  await app.mouse.move(picture.x + picture.width * 0.2, picture.y + picture.height * 0.2)
  await app.mouse.down()
  await app.mouse.move(picture.x + picture.width * 0.6, picture.y + picture.height * 0.6, { steps: 6 })
  await app.mouse.up()
  const comment = dialog.getByRole("textbox")
  await comment.fill("the logo corner")
  await comment.press("Enter")
  await dialog.getByRole("button", { name: "Save", exact: true }).click()
  await expect(dialog).toHaveCount(0)

  await prompt.click()
  await app.keyboard.type("Look at @READ")
  await app.getByRole("option", { name: "README.md" }).click()
  await app.keyboard.type(` ${acpScriptToken("ack")}`)
  await app.keyboard.press("Enter")

  await expect(app.getByText("Received the attachments")).toBeVisible()
  const messages = await api.messages(workspace.directory, session.id)
  const sent = JSON.stringify(messages.find((message) => message.info.role === "user")?.parts ?? [])
  expect(sent).toContain("image/png")
  expect(sent).toContain("README.md")
  expect(sent).toContain("the logo corner")
})

test("06 a new session starts on the folder's harness, then on the harness last used for a draft in the workspace", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("defaults")
  const existing = await api.createSession(workspace.directory, { title: "Existing", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, existing.id)}`)
  await expect(app.getByRole("textbox", { name: UI.composer })).toBeVisible()
  const picker = app.locator('[data-action="prompt-harness-model"]').filter({ visible: true })
  const openDraft = async () => {
    await app.getByRole("main").getByRole("button", { name: UI.newSession, exact: true }).click()
    await expect(app).toHaveURL(new RegExp(`${sessionRoute(workspace.id)}$`))
  }

  await openDraft()
  await expect(picker).toHaveAttribute("data-harness", "pi")
  await picker.click()
  await app.getByRole("button", { name: /^Harness/ }).click()
  await app.getByRole("button", { name: "Scripted ACP" }).click()
  await expect(picker).toHaveAttribute("data-harness", "scripted-acp")
  await app.keyboard.press("Escape")
  await sendPrompt(app, "Start on the scripted agent")
  await expect.poll(async () => (await api.sessions(workspace.directory)).length).toBe(2)
  const created = (await api.sessions(workspace.directory)).find((row) => row.id !== existing.id)
  expect(JSON.stringify(created)).toContain('"harness":{"id":"scripted-acp","access":"connection"}')

  await app.reload()
  await expect(app.getByRole("textbox", { name: UI.composer })).toBeVisible()
  await openDraft()
  await expect(picker).toHaveAttribute("data-harness", "scripted-acp")
})

test("06 a draft and the prompt history survive a reload, and a shell command is sent as plain text", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("persist")
  await stack.acp.write("persist", { steps: [{ kind: "text", text: "Noted" }] })
  const session = await api.createSession(workspace.directory, { title: "Persist", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const prompt = app.getByRole("textbox", { name: UI.composer })
  await sendPrompt(app, `Remember this prompt ${acpScriptToken("persist")}`)
  await expect(app.getByText("Noted")).toBeVisible()
  await prompt.fill("A draft that outlives a reload")
  await app.reload()
  await expect(prompt).toHaveText("A draft that outlives a reload")
  await prompt.press("ControlOrMeta+a")
  await prompt.press("Backspace")
  await expect(app.getByRole("button", { name: UI.sendIdle })).toBeVisible()
  await prompt.press("ArrowUp")
  await expect(prompt).toContainText("Remember this prompt")

  await prompt.fill("")
  await prompt.press("!")
  const shell = app.getByRole("textbox", { name: /^Enter shell command/ })
  await expect(shell).toBeVisible()
  await shell.pressSequentially("echo shell-text")
  await expect(app.getByRole("button", { name: UI.send, exact: true })).toBeEnabled()
  await shell.press("Enter")
  await expect(prompt).toBeVisible()
  await expect.poll(async () => JSON.stringify(await api.messages(workspace.directory, session.id))).toContain('"text":"echo shell-text"')
})

test("06 typing anywhere on the session starts a message in the composer", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("type-to-focus")
  const session = await api.createSession(workspace.directory, { title: "Type to focus", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const prompt = app.getByRole("textbox", { name: UI.composer })
  await expect(prompt).toBeVisible()
  await app.evaluate(() => {
    if (document.activeElement instanceof HTMLElement) document.activeElement.blur()
  })
  await app.keyboard.press("x")
  await expect(prompt).toBeFocused()
  await expect(prompt).toHaveText("x")
})

test("06 a file dropped on the transcript is attached to the composer", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("drop")
  await stack.acp.write("drop", { steps: [{ kind: "text", text: "A reply to drop files onto" }] })
  const session = await api.createSession(workspace.directory, { title: "Drop", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const prompt = app.getByRole("textbox", { name: UI.composer })
  await sendPrompt(app, `Say something ${acpScriptToken("drop")}`)
  const reply = app.getByText("A reply to drop files onto")
  await expect(reply).toBeVisible()
  const transfer = await app.evaluateHandle(() => {
    const data = new DataTransfer()
    data.items.add(new File([new Uint8Array([137, 80, 78, 71])], "dropped.png", { type: "image/png" }))
    return data
  })
  await reply.dispatchEvent("dragover", { dataTransfer: transfer })
  await reply.dispatchEvent("drop", { dataTransfer: transfer })
  await expect(app.getByRole("button", { name: "Remove attachment" })).toBeVisible()
})

test("06 a Claude session created on an explicit model id keeps that model across a switch away and back, and sends it", async ({ stack, api, app, isMobile }) => {
  test.skip(isMobile, "the switch goes through the desktop rail")
  const availability = await installedCli("claude")
  test.skip(!availability.available, availability.available ? "" : availability.reason)
  const workspace = await stack.daemon.makeWorkspace("explicit-model")
  const model = { providerId: "claude", modelId: "claude-haiku-4-5-20251001" }
  const haiku = await api.createSession(workspace.directory, { title: "Explicit model", harness: { id: "claude", access: "native" }, model })
  const other = await api.createSession(workspace.directory, { title: "Elsewhere", harness: SCRIPTED_ACP_HARNESS })
  const rail = app.getByRole("navigation", { name: UI.rail })
  const pane = (id: string) => app.locator(`[data-testid="session-page-root"][data-session-id="${id}"]`)
  const trigger = app.locator('[data-action="prompt-harness-model"]').filter({ visible: true })
  const options = app.waitForResponse((response) => response.url().includes("/agent-config/harness/options") && response.url().includes(`sessionId=${haiku.id}`))

  await app.goto(`${stack.url}${sessionRoute(workspace.id, haiku.id)}`)
  expect((await options).ok()).toBe(true)
  await expect(trigger).toHaveAttribute("data-ready-for-submit", "true")
  await expect(trigger.locator('[data-slot="composer-control-label"]')).toHaveText("Haiku")

  await rail.getByRole("button", { name: "Elsewhere", exact: true }).click()
  await expect(pane(other.id)).toBeVisible()
  await rail.getByRole("button", { name: "Explicit model", exact: true }).click()
  await expect(pane(haiku.id)).toBeVisible()
  await expect(trigger).toHaveAttribute("data-ready-for-submit", "true")
  await expect(trigger.locator('[data-slot="composer-control-label"]')).toHaveText("Haiku")

  await sendPrompt(app, "Reply with exactly this one token: HKU")
  const sent = () => stack.scripted.requests.filter((request) => request.prompt.includes("HKU")).map((request) => request.model)
  await expect.poll(sent, { timeout: 60_000 }).toContain(model.modelId)
  expect(sent()).not.toContain("claude-opus-5-5")
})

test("06 a closed tooltip holds no tooltip machinery until the pointer reaches it, and then opens on hover as before", async ({ stack, api, app, isMobile }) => {
  test.skip(isMobile, "hover tooltips are a pointer device's")
  const workspace = await stack.daemon.makeWorkspace("tooltip")
  const session = await api.createSession(workspace.directory, { title: "Tooltip", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const chip = app.locator('[data-action="prompt-permission-mode"]').filter({ visible: true })
  await expect(chip).toBeVisible()
  const trigger = app.locator('[data-component="tooltip-v2-trigger"]').filter({ has: chip })
  const cdp = await app.context().newCDPSession(app)
  const listeners = async () => {
    await trigger.evaluate((element) => ((window as unknown as { __tooltipTrigger: Element }).__tooltipTrigger = element))
    const { result } = await cdp.send("Runtime.evaluate", { expression: "window.__tooltipTrigger" })
    const { listeners: attached } = await cdp.send("DOMDebugger.getEventListeners", { objectId: result.objectId! })
    return [...new Set(attached.map((listener) => listener.type))].sort()
  }

  const closed = await listeners()
  expect(closed).not.toContain("focus")
  expect(closed).not.toContain("blur")
  expect(await trigger.getAttribute("data-closed")).toBe("")
  expect(await trigger.getAttribute("aria-describedby")).toBeNull()

  await chip.hover()
  await expect(app.getByRole("tooltip")).toBeVisible()
  expect(await listeners()).toEqual(expect.arrayContaining(["blur", "focus"]))
  await app.mouse.move(0, 0)
  await expect(app.getByRole("tooltip")).toHaveCount(0)
})

test("06 keyboard focus on a control inside a tooltip trigger opens no tooltip, before or after a pointer has woken it", async ({ stack, api, app, isMobile }) => {
  test.skip(isMobile, "hover tooltips are a pointer device's")
  const workspace = await stack.daemon.makeWorkspace("tooltip-focus")
  const session = await api.createSession(workspace.directory, { title: "Tooltip focus", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const chip = app.locator('[data-action="prompt-permission-mode"]').filter({ visible: true })
  await expect(chip).toBeVisible()
  const tabOntoChip = async () => {
    await app.getByRole("textbox", { name: UI.composer }).click()
    for (let step = 0; step < 16 && !(await chip.evaluate((element) => element === document.activeElement)); step++) await app.keyboard.press("Tab")
    await expect(chip).toBeFocused()
    await app.evaluate(() => new Promise((painted) => requestAnimationFrame(() => requestAnimationFrame(painted))))
    await expect(app.getByRole("tooltip")).toHaveCount(0)
  }

  await tabOntoChip()
  await chip.hover()
  await expect(app.getByRole("tooltip")).toBeVisible()
  await app.mouse.move(0, 0)
  await expect(app.getByRole("tooltip")).toHaveCount(0)
  await tabOntoChip()
})

test("06 a tooltip forced open by the send button's flash closes as it opened and leaves its trigger closed", async ({ stack, api, app, isMobile }) => {
  test.skip(isMobile, "the send button's flash is checked at desktop width")
  test.setTimeout(60_000)
  const workspace = await stack.daemon.makeWorkspace("tooltip-forced")
  await stack.acp.write("deaf", { steps: [{ kind: "text", text: "Started and deaf to Stop" }, { kind: "hold", name: "deaf", ignoresCancel: true }] })
  const session = await api.createSession(workspace.directory, { title: "Tooltip forced", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  await sendPrompt(app, `Start. ${acpScriptToken("deaf")}`)
  await expect(app.getByText("Started and deaf to Stop")).toBeVisible()
  const submit = app.locator('[data-action="prompt-submit"]').filter({ visible: true })
  const trigger = app.locator('[data-component="tooltip-v2-trigger"]').filter({ has: submit })
  await submit.focus()
  await app.keyboard.press("Enter")
  await expect(app.getByRole("status").filter({ hasText: "The agent stopped responding" })).toBeVisible({ timeout: 15_000 })
  await app.getByRole("textbox", { name: UI.composer }).click()
  await app.keyboard.type("held by a deaf agent")

  await submit.focus()
  await app.keyboard.press("Enter")
  await expect(app.getByRole("tooltip")).toBeVisible()
  await expect(app.getByRole("tooltip")).toHaveCount(0, { timeout: 10_000 })
  await expect(trigger).toHaveAttribute("data-closed", "")
  await expect(trigger).not.toHaveAttribute("data-expanded")
  await expect(trigger).not.toHaveAttribute("aria-describedby")
  await stack.acp.release("deaf")
})

test("06 a menu that has never opened holds no menu machinery, and its first press opens it", async ({ stack, api, app, isMobile }) => {
  test.skip(isMobile, "the composer toolbar's add menu is checked at desktop width")
  const workspace = await stack.daemon.makeWorkspace("menu-closed")
  const session = await api.createSession(workspace.directory, { title: "Menu", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const trigger = app.locator('[data-action="prompt-add"]').filter({ visible: true })
  await expect(trigger).toBeEnabled()
  const cdp = await app.context().newCDPSession(app)
  await trigger.evaluate((element) => ((window as unknown as { __menuTrigger: Element }).__menuTrigger = element))
  const { result } = await cdp.send("Runtime.evaluate", { expression: "window.__menuTrigger" })
  const { listeners } = await cdp.send("DOMDebugger.getEventListeners", { objectId: result.objectId! })
  expect(listeners.map((listener) => listener.type)).not.toContain("focus")
  await expect(trigger).toHaveAttribute("aria-haspopup", "true")
  await expect(trigger).toHaveAttribute("aria-expanded", "false")
  await expect(trigger).toHaveAttribute("data-closed", "")
  await expect(trigger).toHaveAttribute("id", /-trigger$/)

  await trigger.click()
  await expect(app.getByRole("menu")).toBeVisible()
  await expect(trigger).toHaveAttribute("aria-expanded", "true")
  await expect(app.getByRole("menu")).toHaveAttribute("aria-labelledby", (await trigger.getAttribute("id"))!)
  await app.keyboard.press("Escape")
  await expect(app.getByRole("menu")).toHaveCount(0)
})

test("06 the first key on a never-opened menu trigger opens the menu on its first item, and typing moves to a match", async ({ stack, api, app, isMobile }) => {
  test.skip(isMobile, "the composer toolbar's add menu is checked at desktop width")
  const workspace = await stack.daemon.makeWorkspace("menu-keys")
  const session = await api.createSession(workspace.directory, { title: "Menu keys", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const trigger = app.locator('[data-action="prompt-add"]').filter({ visible: true })
  await expect(trigger).toBeEnabled()
  await trigger.focus()

  await app.keyboard.press("ArrowDown")
  const menu = app.getByRole("menu")
  await expect(menu).toBeVisible()
  await expect(menu.getByRole("menuitem").first()).toBeFocused()
  const items = menu.locator('[role="menuitem"]:not([aria-disabled="true"])')
  const labels = (await items.allTextContents()).map((label) => label.trim())
  const target = labels.findIndex((label, index) => index > 0 && labels.filter((other) => other[0]?.toLowerCase() === label[0]?.toLowerCase()).length === 1)
  expect(target).toBeGreaterThan(0)
  await app.keyboard.press(labels[target][0].toLowerCase())
  await expect(items.nth(target)).toBeFocused()
})
