import { expect, sendPrompt, sessionRoute, test } from "../harness"

test("06 effort picker: an OpenCode model's effort variants show in the picker, and the chosen one is the variant the engine runs", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("opencode-effort")
  const session = await api.createSession(workspace.directory, { title: "OpenCode effort", harness: { id: "opencode", access: "native" },
    model: { providerId: "anthropic", modelId: "claude-sonnet-4-5" } })
  stack.scripted.scriptText({ marker: "EFFORTPICKED", text: "EFFORTPICKED" })
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  await app.getByRole("button", { name: /^Select harness and model/ }).click()
  const picker = app.getByRole("dialog", { name: "Select harness, model and effort" })
  const effort = picker.getByRole("slider", { name: "Effort" })
  await expect(effort).toBeVisible()
  await effort.focus()
  await app.keyboard.press("End")
  const chosen = await effort.getAttribute("aria-valuetext")
  expect(chosen).toBeTruthy()
  await expect.poll(async () => (await api.sessionConfig(workspace.directory, session.id)).variant?.toLowerCase()).toBe(chosen?.toLowerCase())
  await app.keyboard.press("Escape")
  await sendPrompt(app, "Reply with exactly EFFORTPICKED")
  await expect(app.getByText("EFFORTPICKED", { exact: true }).last()).toBeVisible()
  const sent = (await api.messages(workspace.directory, session.id)).find((message) => message.info.role === "user")?.info as { variant?: string } | undefined
  expect(sent?.variant?.toLowerCase()).toBe(chosen?.toLowerCase())
  await app.reload()
  stack.scripted.scriptText({ marker: "EFFORTKEPT", text: "EFFORTKEPT" })
  await sendPrompt(app, "Reply with exactly EFFORTKEPT")
  await expect(app.getByText("EFFORTKEPT", { exact: true }).last()).toBeVisible()
  const followup = (await api.messages(workspace.directory, session.id)).filter((message) => message.info.role === "user").at(-1)?.info as { variant?: string } | undefined
  expect(followup?.variant?.toLowerCase()).toBe(chosen?.toLowerCase())
})

test("06 effort picker: a new Claude session retains its draft effort after creation and reload", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("claude-draft-effort")
  await app.goto(`${stack.url}${sessionRoute(workspace.id)}`)
  await app.getByRole("button", { name: /^Select harness and model/ }).click()
  await app.getByRole("button", { name: /^Harness/ }).click()
  await app.getByRole("button", { name: "Claude Code", exact: true }).click()
  const picker = app.getByRole("dialog", { name: "Select harness, model and effort" })
  const effort = picker.getByRole("slider", { name: "Effort" })
  await expect(effort).toBeVisible()
  await effort.focus()
  await app.keyboard.press("End")
  const chosen = await effort.getAttribute("aria-valuetext")
  expect(chosen).toBeTruthy()
  await app.keyboard.press("Escape")
  await sendPrompt(app, "Reply with exactly this one token: DRAFTEFFORT")
  await expect(app.getByText("DRAFTEFFORT", { exact: true }).last()).toBeVisible()
  const sessions = await api.sessions(workspace.directory)
  expect(sessions).toHaveLength(1)
  const session = sessions[0]
  await app.reload()
  await sendPrompt(app, "Reply with exactly this one token: FOLLOWUPEFFORT")
  await expect(app.getByText("FOLLOWUPEFFORT", { exact: true }).last()).toBeVisible()
  const users = (await api.messages(workspace.directory, session.id)).filter((message) => message.info.role === "user")
  expect(users).toHaveLength(2)
  for (const user of users) expect((user.info as { variant?: string }).variant?.toLowerCase()).toBe(chosen?.toLowerCase())
})
