import fs from "node:fs/promises"
import path from "node:path"
import type { Locator, Page } from "@playwright/test"
import { acpScriptToken, expect, SCRIPTED_ACP_HARNESS, sendPrompt, sessionRoute, test, UI } from "../harness"

async function dragAcross(page: Page, target: Locator, from = 0) {
  await target.hover()
  const box = await target.boundingBox()
  if (!box) throw new Error("the text to select is not on screen")
  const y = box.y + Math.min(box.height / 2, 8)
  await page.mouse.move(box.x + 2 + box.width * from, y)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width - 2, y, { steps: 8 })
  await page.mouse.up()
}

const selectedText = (page: Page) => page.evaluate(() => document.getSelection()?.toString() ?? "")
const editHighlights = (page: Page) => page.evaluate(() => CSS.highlights.get("composer-quote-edit")?.size ?? 0)

async function annotateMarkdown(page: Page, panel: Locator, comment: string) {
  await dragAcross(page, panel.getByText("Back up the database before every deploy."))
  await expect(page.getByRole("textbox", { name: "Add comment" })).toBeVisible()
  await page.keyboard.type(comment)
  await page.keyboard.press("Enter")
}

test("06 text selected in the transcript, a markdown file or a code file opens a comment box; Enter adds it to the composer's annotations, which can be edited in place, removed and sent", async ({ stack, api, app, isMobile }, testInfo) => {
  test.skip(isMobile, "selecting by pointer drag and the side panel are desktop gestures")
  const workspace = await stack.daemon.makeWorkspace("selection-comments")
  await fs.writeFile(path.join(workspace.directory, "notes.md"), "# Deploy notes\n\nBack up the database before every deploy.\n")
  await fs.writeFile(path.join(workspace.directory, "answer.ts"), "export const answer = 42\n")
  await stack.acp.write("plan", { steps: [{ kind: "text", text: "Run the migration before the deploy." }] })
  await stack.acp.write("answer", { steps: [{ kind: "text", text: "Read your three comments." }] })
  const session = await api.createSession(workspace.directory, { title: "Selection comments", harness: SCRIPTED_ACP_HARNESS })
  await api.prompt(workspace.directory, session.id, `How do I deploy? ${acpScriptToken("plan")}`)

  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  await expect(app.getByRole("button", { name: UI.sendIdle })).toBeVisible()
  const reply = app.getByText("Run the migration before the deploy.")
  await dragAcross(app, reply)
  const box = app.getByRole("textbox", { name: "Add comment" })
  await expect(box).toBeVisible()
  await expect(box, "the box waits for a key, so the selection can still be copied").not.toBeFocused()
  expect(await selectedText(app)).toContain("migration")
  await app.keyboard.type("Why before?")
  await expect(box).toHaveValue("Why before?")
  await app.keyboard.press("Enter")
  await expect(box).toHaveCount(0)
  await expect(app.getByRole("button", { name: "1 annotation", exact: true })).toBeVisible()

  await dragAcross(app, reply)
  await expect(box).toBeVisible()
  await app.keyboard.press("Escape")
  await expect(box, "Escape closes the box without adding a comment").toHaveCount(0)
  await expect(app.getByRole("button", { name: "1 annotation", exact: true })).toBeVisible()

  await app.getByRole("button", { name: UI.openPanel }).click()
  const panel = app.getByRole("complementary", { name: "Workspace panel" })
  await panel.getByRole("treeitem", { name: /^notes\.md/ }).click()
  await annotateMarkdown(app, panel, "Is this still true?")
  const annotations = app.getByRole("button", { name: "2 annotations", exact: true })
  await expect(annotations).toBeVisible()

  await panel.getByRole("treeitem", { name: /^answer\.ts/ }).click()
  await dragAcross(app, panel.getByText("export const answer = 42").first(), 0.5)
  await expect(panel.getByRole("textbox", { name: "Add comment" })).toBeFocused()
  await app.keyboard.type("Why 42?")
  await app.keyboard.press("Enter")
  await expect(app.getByRole("button", { name: "Remove file from context" })).toHaveCount(1)

  await annotations.hover()
  await expect(app.getByText("Selected text in the conversation")).toBeVisible()
  await expect(app.getByText("Selected text in notes.md")).toBeVisible()
  await testInfo.attach("annotation-card", { body: await app.screenshot({ path: testInfo.outputPath("annotation-card.png") }), contentType: "image/png" })
  await app.getByRole("button", { name: "Edit annotation" }).first().click()
  const editor = app.getByRole("textbox", { name: "Add comment" })
  await expect(editor).toHaveValue("Why before?")
  await expect(editor).toBeFocused()
  await expect.poll(() => editHighlights(app), "the annotated text is painted while it is edited").toBe(1)
  await testInfo.attach("annotation-edit", { body: await app.screenshot({ path: testInfo.outputPath("annotation-edit.png") }), contentType: "image/png" })
  await editor.fill("Why before the deploy?")
  await editor.press("Enter")
  await expect(editor).toHaveCount(0)
  await expect.poll(() => editHighlights(app)).toBe(0)

  await annotations.hover()
  await expect(app.getByText("Why before the deploy?")).toBeVisible()
  await app.getByRole("button", { name: "Edit annotation" }).nth(1).click()
  await expect(panel.getByText("Back up the database before every deploy.")).toBeVisible()
  await expect(editor).toHaveValue("Is this still true?")
  await expect.poll(() => editHighlights(app)).toBe(1)
  await editor.fill("Discard this change")
  await editor.press("Escape")
  await expect(editor).toHaveCount(0)
  await expect.poll(() => editHighlights(app)).toBe(0)
  await annotations.hover()
  await expect(app.getByText("Is this still true?")).toBeVisible()
  await app.getByRole("button", { name: "Remove annotation" }).nth(1).click()
  await expect(app.getByRole("button", { name: "1 annotation", exact: true })).toBeVisible()
  await annotateMarkdown(app, panel, "Is this still true?")
  await expect(annotations).toBeVisible()

  await sendPrompt(app, `Answer my comments. ${acpScriptToken("answer")}`)
  await expect(app.getByText("Read your three comments.")).toBeVisible()
  await expect(annotations, "sending empties the composer's annotations").toHaveCount(0)
  const transcript = app.getByTestId("session-page-root")
  await expect(transcript.getByText("Why before the deploy?")).toBeVisible()
  await expect(transcript.getByText("Is this still true?")).toBeVisible()
  await expect(transcript.getByText("Why 42?")).toBeVisible()
  const sent = JSON.stringify(await api.messages(workspace.directory, session.id))
  expect(sent).toContain("this excerpt from the conversation:\\n> Run the migration before the deploy.\\n\\nWhy before the deploy?")
  expect(sent).toContain("this excerpt from the file notes.md:\\n> Back up the database before every deploy.\\n\\nIs this still true?")
  expect(sent).toContain("regarding line 1 of answer.ts: Why 42?")
})

test("06 phone: tapping the annotations chip opens its card, edits and clears comments without horizontal overflow", async ({ stack, api, app, isMobile }) => {
  test.skip(!isMobile, "this flow exercises the touch controls")
  const workspace = await stack.daemon.makeWorkspace("touch-annotations")
  await stack.acp.write("reply", { steps: [{ kind: "text", text: "Run the migration before the deploy." }] })
  await stack.acp.write("answer", { steps: [{ kind: "text", text: "I read your edited comment." }] })
  const session = await api.createSession(workspace.directory, { title: "Touch annotations", harness: SCRIPTED_ACP_HARNESS })
  await api.prompt(workspace.directory, session.id, `How do I deploy? ${acpScriptToken("reply")}`)
  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  const reply = app.getByText("Run the migration before the deploy.")
  await expect(reply).toBeVisible()
  await reply.evaluate((element) => {
    const range = document.createRange()
    range.selectNodeContents(element)
    document.getSelection()?.removeAllRanges()
    document.getSelection()?.addRange(range)
  })
  const editor = app.getByRole("textbox", { name: "Add comment" })
  await expect(editor).toBeVisible()
  await editor.fill("Why before?")
  await app.getByRole("button", { name: "Comment", exact: true }).tap()
  const annotations = app.getByRole("button", { name: "1 annotation", exact: true })
  await expect(annotations).toBeVisible()
  await annotations.tap()
  const card = app.getByRole("dialog", { name: "Show annotations" })
  await expect(card).toBeVisible()
  const edit = card.getByRole("button", { name: "Edit annotation" })
  const target = await edit.boundingBox()
  expect(target?.width).toBeGreaterThanOrEqual(44)
  expect(target?.height).toBeGreaterThanOrEqual(44)
  await edit.tap()
  await expect(editor).toHaveValue("Why before?")
  await expect.poll(() => editHighlights(app)).toBe(1)
  await editor.fill("Why before the deploy?")
  await app.getByRole("button", { name: "Save", exact: true }).tap()
  await expect(editor).toHaveCount(0)
  await expect.poll(() => editHighlights(app)).toBe(0)
  await annotations.tap()
  await expect(card.getByText("Why before the deploy?")).toBeVisible()
  expect(await app.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(0)
  await sendPrompt(app, `Answer my comment. ${acpScriptToken("answer")}`)
  await expect(app.getByText("I read your edited comment.")).toBeVisible()
  await expect(annotations).toHaveCount(0)
  expect(JSON.stringify(await api.messages(workspace.directory, session.id))).toContain("Why before the deploy?")
})
