import fs from "node:fs/promises"
import path from "node:path"
import type { Locator } from "@playwright/test"
import { apiRequests, expect, expectNothingAnimating, git, SCRIPTED_ACP_HARNESS, sessionRoute, test, UI, watchPageWork } from "../harness"

test.skip(({ isMobile }) => isMobile, "flow 14 runs at desktop width")

test("14 switching back to a session whose panel was open shows the files tree as it was, without reading its folders again", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("return")
  await fs.mkdir(path.join(workspace.directory, "docs"), { recursive: true })
  await fs.writeFile(path.join(workspace.directory, "docs/notes.md"), "notes\n")
  await git(workspace.directory, "add", "-A")
  await git(workspace.directory, "commit", "-qm", "docs")
  const withPanel = await api.createSession(workspace.directory, { title: "With panel", harness: SCRIPTED_ACP_HARNESS })
  await api.createSession(workspace.directory, { title: "Without panel", harness: SCRIPTED_ACP_HARNESS })

  await app.goto(`${stack.url}${sessionRoute(workspace.id, withPanel.id)}`)
  await expect(app.getByRole("button", { name: UI.sendIdle })).toBeVisible()
  await app.getByRole("button", { name: UI.openPanel }).click()
  const panel = app.getByRole("complementary", { name: "Workspace panel" })
  await panel.getByRole("treeitem", { name: "docs", exact: true }).click()
  await expect(panel.getByRole("treeitem", { name: /^notes\.md/ })).toBeVisible()
  const settled = apiRequests(app, stack.url)
  await settled()
  await expectNothingAnimating(app)
  const work = await watchPageWork(app, { nodes: { tree: '[data-component="filetree"]' } })
  const rail = app.getByRole("navigation", { name: UI.rail })
  await rail.getByRole("button", { name: "Without panel", exact: true }).click()
  await expect(app.getByRole("button", { name: UI.openPanel })).toBeVisible()
  await expect(panel).toHaveCount(0)
  await expect.poll(() => app.locator('[data-component="filetree"]').count(), { message: "the hidden tree unmounts" }).toBe(0)
  await expectNothingAnimating(app)
  await rail.getByRole("button", { name: "With panel", exact: true }).click()
  await expect(panel.getByRole("treeitem", { name: /^notes\.md/ })).toBeVisible()
  await expectNothingAnimating(app)

  const seen = await work()
  expect(seen.removed.tree ?? 0, "files trees removed while the panel was hidden").toBe(1)
  expect(seen.added.tree ?? 0, "files trees added on return").toBe(1)
  const folderReads = (await settled()).filter((request) => /^\/api\/wr\/file(\/|$)/.test(request))
  expect(folderReads, "folder reads on return").toEqual([])
  expect((await api.session(workspace.directory, withPanel.id)).title).toBe("With panel")
})

test("14 the files tree and the Changes groups come back where they were after the panel hides and after the navigator switches", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("restore")
  const folders = Array.from({ length: 12 }, (_, index) => `dir-${String(index).padStart(2, "0")}`)
  const names = folders.flatMap((folder, index) => Array.from({ length: 12 }, (_, item) => `${folder}/n-${String(index * 12 + item).padStart(3, "0")}.ts`))
  for (const folder of folders) await fs.mkdir(path.join(workspace.directory, folder))
  for (const name of names) await fs.writeFile(path.join(workspace.directory, name), "export const value = 0\n")
  await git(workspace.directory, "add", "-A")
  await git(workspace.directory, "commit", "-qm", "twelve folders")
  for (const name of names.slice(0, 80)) await fs.writeFile(path.join(workspace.directory, name), "export const value = 1\n")
  await git(workspace.directory, "add", ...names.slice(0, 5))
  const withPanel = await api.createSession(workspace.directory, { title: "With panel", harness: SCRIPTED_ACP_HARNESS })
  await api.createSession(workspace.directory, { title: "Without panel", harness: SCRIPTED_ACP_HARNESS })

  await app.clock.install()
  await app.goto(`${stack.url}${sessionRoute(workspace.id, withPanel.id)}`)
  await expect(app.getByRole("button", { name: UI.sendIdle })).toBeVisible()
  await app.getByRole("button", { name: UI.openPanel }).click()
  const panel = app.getByRole("complementary", { name: "Workspace panel" })
  const row = (name: string) => panel.getByRole("treeitem", { name: new RegExp(`^${name.replaceAll(".", "\\.")}`) })
  const treeScroller = () => panel.getByTestId("workspace-files-navigator").locator("[data-scrollable]").first()
  const groups = () => panel.getByTestId("source-control-groups")
  const distance = (scroller: Locator, top: number) => scroller.evaluate((element, wanted) => Math.abs(element.scrollTop - wanted), top)
  for (const folder of folders.toReversed()) await panel.getByRole("treeitem", { name: folder, exact: true }).click()
  await expect(row("n-000.ts")).toBeVisible()
  await treeScroller().evaluate((element) => (element.scrollTop = 600))
  await expect.poll(() => distance(treeScroller(), 600)).toBeLessThanOrEqual(1)
  await expect(row("n-025.ts")).toBeVisible()

  const rail = app.getByRole("navigation", { name: UI.rail })
  await rail.getByRole("button", { name: "Without panel", exact: true }).click()
  await expect(panel).toHaveCount(0)
  await expect.poll(() => app.locator('[data-component="filetree"]').count(), { message: "the hidden tree unmounts" }).toBe(0)
  await rail.getByRole("button", { name: "With panel", exact: true }).click()
  await expect(row("n-025.ts")).toBeVisible()
  await expect.poll(() => distance(treeScroller(), 600), { message: "tree scroll after the panel hid" }).toBeLessThanOrEqual(1)

  await panel.getByRole("button", { name: "Open Changes" }).click()
  await expect(panel.getByTestId("workspace-files-navigator")).toHaveCount(0)
  await panel.getByRole("button", { name: "Open Files" }).click()
  await expect(row("n-025.ts")).toBeVisible()
  await expect.poll(() => distance(treeScroller(), 600), { message: "tree scroll after the navigator switched" }).toBeLessThanOrEqual(1)
  await expectNothingAnimating(app)

  await panel.getByPlaceholder("Search files...").pressSequentially("n-14")
  await expect(row("n-143.ts")).toBeVisible()
  await expect(row("n-025.ts")).toBeHidden()
  await panel.getByRole("button", { name: "Open Changes" }).click()
  await panel.getByRole("button", { name: "Open Files" }).click()
  await expect(panel.getByPlaceholder("Search files...")).toHaveValue("n-14")
  await expect(row("n-143.ts")).toBeVisible()
  await expect(row("n-025.ts")).toBeHidden()

  await panel.getByRole("button", { name: "Open Changes" }).click()
  const staged = panel.getByTestId("source-control-section-staged").getByRole("button", { name: /^Staged changes/ })
  await expect(panel.getByTestId("source-control-row").filter({ has: app.getByText("n-079.ts") })).toHaveCount(1)
  await staged.click()
  await expect(staged).toHaveAttribute("aria-expanded", "false")
  await groups().evaluate((element) => (element.scrollTop = 400))
  await expect.poll(() => distance(groups(), 400)).toBeLessThanOrEqual(1)
  await panel.getByRole("button", { name: "Open Files" }).click()
  await expect(groups()).toHaveCount(0)
  await panel.getByRole("button", { name: "Open Changes" }).click()
  await expect(staged).toHaveAttribute("aria-expanded", "false")
  await expect.poll(() => distance(groups(), 400), { message: "groups scroll after the navigator switched" }).toBeLessThanOrEqual(1)

  await app.getByRole("button", { name: "Close workspace panel" }).click()
  await expect(groups()).toHaveCount(0)
  await expectNothingAnimating(app)
  await app.clock.fastForward("11:00")
  const reads = apiRequests(app, stack.url)
  await app.getByRole("button", { name: UI.openPanel }).click()
  await expect(staged).toHaveAttribute("aria-expanded", "false")
  await expect.poll(() => distance(groups(), 400), { message: "groups scroll after the status was read again" }).toBeLessThanOrEqual(1)
  expect((await reads()).filter((request) => request === "/api/wr/git/status"), "status read again once its cache expired").toHaveLength(1)
})

test("14 rows a folder showed with Show more stay shown after the navigator switches", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("show-more")
  await fs.mkdir(path.join(workspace.directory, "many"))
  for (let index = 0; index < 40; index += 1) await fs.writeFile(path.join(workspace.directory, `many/m-${String(index).padStart(2, "0")}.ts`), "export {}\n")
  await git(workspace.directory, "add", "-A")
  await git(workspace.directory, "commit", "-qm", "forty files")
  const session = await api.createSession(workspace.directory, { title: "Show more", harness: SCRIPTED_ACP_HARNESS })

  await app.goto(`${stack.url}${sessionRoute(workspace.id, session.id)}`)
  await expect(app.getByRole("button", { name: UI.sendIdle })).toBeVisible()
  await app.getByRole("button", { name: UI.openPanel }).click()
  const panel = app.getByRole("complementary", { name: "Workspace panel" })
  const last = panel.getByRole("treeitem", { name: /^m-39\.ts/ })
  const toBottom = () => panel.getByTestId("workspace-files-navigator").locator("[data-scrollable]").first().evaluate((element) => (element.scrollTop = element.scrollHeight))
  await panel.getByRole("treeitem", { name: "many", exact: true }).click()
  await panel.getByRole("button", { name: /^Show \d+ more$/ }).click()
  await toBottom()
  await expect(last).toBeVisible()

  await panel.getByRole("button", { name: "Open Changes" }).click()
  await expect(panel.getByTestId("workspace-files-navigator")).toHaveCount(0)
  await panel.getByRole("button", { name: "Open Files" }).click()
  await expect(panel.getByRole("tree")).toBeVisible()
  await toBottom()
  await expect(last).toBeVisible()
})
