import { acpScriptToken, expect, SCRIPTED_ACP_HARNESS, test, UI, type Account } from "../harness"
import { sidebarFilter } from "../harness/sidebar-filter"
import { ownersColleague, sharing } from "./47-sharing.controls"
import { sharedProjectReceipt, sharedReaderPage } from "./47-session-readers.controls"

test("47 shared readers see independently, hide settled sessions, and return on genuine work", async ({ signed, page, isMobile }, testInfo) => {
  const recipient = await ownersColleague(signed, "Grace Reader")
  const workspace = await signed.makeWorkspace("shared-readers", "Reader project")
  const session = await signed.owner.api.createSession(workspace.directory, { title: "Shared reader lifecycle", harness: SCRIPTED_ACP_HARNESS })
  await sharing(signed, { workspaceId: workspace.id, sessionId: session.id, userId: recipient.userId })("POST", "follow")
  const readerPage = (account: Account = recipient, query: Readonly<Record<string, string>> = {}) => sharedReaderPage(signed, account, workspace.id, session.id, query)
  await signed.local.acp.write("shared-reader-first", { steps: [{ kind: "text", text: "Read this shared result" }] })
  await signed.owner.api.prompt(workspace.directory, session.id, `First ${acpScriptToken("shared-reader-first")}`)
  await expect.poll(async () => (await readerPage()).items[0]?.attention?.outcome?.status).toBe("completed")
  const completed = (await readerPage()).items[0]
  const originalOwner = (await readerPage(signed.owner)).items[0]
  await testInfo.attach("shared-project-registration", { body: JSON.stringify(await sharedProjectReceipt(signed, workspace.id)), contentType: "application/json" })
  expect(originalOwner.reader?.seenThrough ?? 0).toBeLessThan(completed.attention.outcome!.sequence)
  await signed.signIn(page, recipient)
  if (isMobile) await page.getByRole("button", { name: UI.openRail }).tap()
  await sidebarFilter(page, "Activity", isMobile)
  const activity = page.getByTestId("activity-sidebar")
  const target = () => activity.getByRole("button", { name: session.title, exact: true })
  await expect(target()).toBeVisible()
  await target().click()
  await expect(page.getByRole("main").getByText("Read this shared result", { exact: true })).toBeVisible()
  await expect.poll(async () => (await readerPage()).items[0]?.reader?.seenThrough).toBeGreaterThanOrEqual(completed.attention.outcome!.sequence)
  if (isMobile) await page.getByRole("button", { name: UI.openRail }).tap()
  await expect(target()).toBeVisible()
  expect((await readerPage(signed.owner)).items[0].reader).toEqual(originalOwner.reader)
  const shown = activity.getByTestId("activity-session-row").filter({ has: page.getByRole("button", { name: session.title, exact: true }) })
  await expect(shown).toHaveCount(1)
  await expect(shown.getByRole("img", { name: /^Unseen/ })).toHaveCount(0)
  await target().focus()
  await shown.getByRole("button", { name: `Settle ${session.title}`, exact: true }).click()
  await expect(target()).toHaveCount(0)
  const settled = (await readerPage()).items[0]
  expect(settled.reader?.settledThrough).toBe(settled.attention.activitySequence)
  expect((await readerPage(signed.owner)).items[0].reader).toEqual(originalOwner.reader)
  await sidebarFilter(page, "Projects", isMobile)
  await expect(page.getByTestId("shared-session-row").filter({ hasText: session.title })).toHaveCount(0)
  expect((await readerPage(recipient, { settled: "active" })).items).toEqual([])
  expect((await readerPage(signed.owner, { settled: "active" })).items.map((row) => row.sessionId)).toEqual([session.id])
  await sidebarFilter(page, "Activity", isMobile)
  const context = await signed.owner.api.createSession(workspace.directory, { title: "Shared reader context", harness: SCRIPTED_ACP_HARNESS })
  await sharing(signed, { workspaceId: workspace.id, sessionId: context.id, userId: recipient.userId })("POST", "follow")
  await activity.getByRole("button", { name: context.title, exact: true }).click()
  const contextPane = page.locator(`[data-testid="session-page-root"][data-session-id="${context.id}"]`)
  const targetPane = page.locator(`[data-testid="session-page-root"][data-session-id="${session.id}"]`)
  await expect(page).toHaveURL(`${signed.url}/w/${workspace.id}/session/${context.id}`)
  await expect(contextPane).toBeVisible()
  await expect(targetPane).toBeHidden()
  if (isMobile) await page.getByRole("button", { name: UI.openRail }).tap()
  await signed.local.acp.write("shared-reader-next", { steps: [{ kind: "hold", name: "shared-reader-running" }, { kind: "text", text: "A fresh shared result" }] })
  await signed.owner.api.promptAsync(workspace.directory, session.id, `Again ${acpScriptToken("shared-reader-next")}`)
  await expect(target()).toBeVisible()
  await expect(shown.locator('[data-sidebar-status="working"]')).toBeVisible()
  await signed.local.acp.release("shared-reader-running")
  await expect(target()).toBeVisible()
  await expect.poll(async () => (await readerPage()).items[0]?.attention.outcome?.sequence).toBeGreaterThan(completed.attention.outcome!.sequence)
  const fresh = (await readerPage()).items[0]
  expect(fresh.attention.outcome!.sequence).toBeGreaterThan(completed.attention.outcome!.sequence)
  await expect(contextPane).toBeVisible()
  await expect(targetPane).toBeHidden()
  await expect(page.getByRole("main").getByText("A fresh shared result", { exact: true })).not.toBeVisible()
  expect(fresh.reader?.seenThrough).toBe(settled.reader!.seenThrough)
})
