import { acpScriptToken, expect, SCRIPTED_ACP_HARNESS, test, UI } from "../harness"
import { sidebarFilter, sidebarHideWorkingStatuses } from "../harness/sidebar-filter"
import { readerRow } from "../harness/session-reader"

test("50 the filter menu hides Working animations, reveals them on row focus, and survives reload", async ({ stack, api, app, isMobile }) => {
  const workspace = await stack.daemon.makeWorkspace("quiet-status")
  const session = await api.createSession(workspace.directory, { title: "Quiet working", harness: SCRIPTED_ACP_HARNESS })
  await stack.acp.write("quiet-status", { steps: [{ kind: "hold", name: "quiet-status" }, { kind: "text", text: "Finished" }] })
  await api.promptAsync(workspace.directory, session.id, `Work ${acpScriptToken("quiet-status")}`)
  const queries: URL[] = []
  app.on("request", (request) => { const url = new URL(request.url()); if (url.pathname.endsWith("/session-list")) queries.push(url) })
  await app.goto(`${stack.url}/`)
  if (isMobile) await app.getByRole("button", { name: UI.openRail }).tap()
  await sidebarFilter(app, "Activity", isMobile)
  const row = app.getByTestId("activity-session-row").filter({ has: app.getByRole("button", { name: session.title, exact: true }) })
  const spinner = row.locator('[data-sidebar-status="working"]')
  await expect(spinner).toBeVisible()
  const before = await row.boundingBox()
  await expect(app.getByRole("button", { name: "Hide working statuses", exact: true })).toHaveCount(0)
  await sidebarHideWorkingStatuses(app, true, isMobile)
  if (!isMobile) await app.mouse.move(900, 500)
  await expect(spinner).toHaveCSS("visibility", "hidden")
  await expect(spinner.locator("span").first()).toHaveCSS("animation-name", "none")
  expect(await row.boundingBox()).toEqual(before)
  await row.getByRole("button", { name: session.title, exact: true }).focus()
  await expect(spinner).toHaveCSS("visibility", "visible")
  if (!isMobile) {
    await app.getByRole("button", { name: "Session options", exact: true }).focus()
    await row.hover()
    await expect(spinner).toHaveCSS("visibility", "visible")
  }
  expect((await readerRow(stack, session.id)).attention.working).toBe(true)
  expect(queries.every((url) => !url.searchParams.has("group") && url.searchParams.get("settled") !== "settled" && url.searchParams.get("settled") !== "all")).toBe(true)
  if (!isMobile) await app.mouse.move(900, 500)
  await app.reload()
  if (isMobile) await app.getByRole("button", { name: UI.openRail }).tap()
  const menu = app.getByRole("button", { name: "Session options", exact: true })
  if (isMobile) await menu.tap()
  else await menu.click()
  const preference = app.getByRole("menuitemcheckbox", { name: "Hide working statuses", exact: true })
  await expect(preference).toHaveAttribute("aria-checked", "true")
  await preference.press("Escape")
  await expect(spinner).toHaveCSS("visibility", "hidden")
  await sidebarHideWorkingStatuses(app, false, isMobile)
  await expect(spinner).toHaveCSS("visibility", "visible")
  await stack.acp.release("quiet-status")
})

test("50 Activity has one aligned failure indicator and recovers through Retry", async ({ stack, api, app, isMobile }) => {
  const workspace = await stack.daemon.makeWorkspace("activity-retry")
  await api.createSession(workspace.directory, { title: "Recovered inventory", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}/`)
  if (isMobile) await app.getByRole("button", { name: UI.openRail }).tap()
  await app.context().setOffline(true)
  await sidebarFilter(app, "Activity", isMobile)
  const area = app.getByTestId("activity-sidebar")
  await expect(area.getByRole("button", { name: "Retry", exact: true })).toHaveCount(1)
  const warning = area.getByRole("status")
  await expect(warning).toHaveCount(1)
  const icon = warning.locator('[data-slot="icon-svg"]')
  await expect(icon).toHaveCount(1)
  const box = await icon.boundingBox()
  expect(box!.width).toBe(12)
  expect(box!.height).toBe(12)
  await app.context().setOffline(false)
  await area.getByRole("button", { name: "Retry", exact: true }).click()
  await expect(area.getByRole("button", { name: "Recovered inventory", exact: true })).toBeVisible()
  await expect(warning).toHaveCount(0)
})

test("50 the filter menu enables one button cycling Activity, Working and Needs you", async ({ stack, api, app, isMobile }) => {
  const workspace = await stack.daemon.makeWorkspace("activity-cycle")
  const idle = await api.createSession(workspace.directory, { title: "Cycle needs you", harness: SCRIPTED_ACP_HARNESS })
  const working = await api.createSession(workspace.directory, { title: "Cycle working", harness: SCRIPTED_ACP_HARNESS })
  await stack.acp.write("activity-cycle", { steps: [{ kind: "hold", name: "activity-cycle" }, { kind: "text", text: "Complete" }] })
  await api.promptAsync(workspace.directory, working.id, `Work ${acpScriptToken("activity-cycle")}`)
  await app.goto(`${stack.url}/`)
  if (isMobile) await app.getByRole("button", { name: UI.openRail }).tap()
  await sidebarFilter(app, "Activity", isMobile)
  const area = app.getByTestId("activity-sidebar")
  const row = (title: string) => area.getByRole("button", { name: title, exact: true })
  const heading = app.locator('[data-slot="session-sidebar-heading"]')
  const cycle = heading.locator("[data-activity-filter]")
  await expect(cycle).toHaveCount(0)
  await sidebarHideWorkingStatuses(app, true, isMobile)
  await expect(cycle).toHaveCount(1)
  if (!isMobile) {
    await app.mouse.move(900, 500)
    await app.evaluate(() => (document.activeElement as HTMLElement | null)?.blur())
    await expect(cycle).toHaveCSS("opacity", "0.65")
  }
  const cycleBox = await cycle.boundingBox()
  const menuBox = await app.getByRole("button", { name: "Session options", exact: true }).boundingBox()
  expect(cycleBox!.x + cycleBox!.width).toBeLessThanOrEqual(menuBox!.x)
  expect(cycleBox!.width).toBeGreaterThanOrEqual(isMobile ? 44 : 28)
  await expect(cycle.locator('[data-icon="circle-dashed"]')).toBeVisible()
  await cycle.click()
  await expect(heading.getByRole("heading", { name: "Working", exact: true })).toBeVisible()
  await expect(row(working.title)).toBeVisible()
  await expect(row(idle.title)).toHaveCount(0)
  await expect(cycle.locator('[data-icon="bell"]')).toBeVisible()
  await cycle.click()
  await expect(heading.getByRole("heading", { name: "Needs you", exact: true })).toBeVisible()
  await expect(row(idle.title)).toBeVisible()
  await expect(row(working.title)).toHaveCount(0)
  await expect(cycle.locator('[data-icon="activity"]')).toBeVisible()
  await expect(cycle.locator("use")).toHaveAttribute("href", /-activity$/)
  await heading.screenshot({ path: test.info().outputPath("activity-pulse.png") })
  await cycle.click()
  await expect(heading.getByRole("heading", { name: "Activity", exact: true })).toBeVisible()
  await expect(row(idle.title)).toBeVisible()
  await expect(row(working.title)).toBeVisible()
  await cycle.click()
  await sidebarHideWorkingStatuses(app, false, isMobile)
  await expect(cycle).toHaveCount(0)
  await expect(heading.getByRole("heading", { name: "Activity", exact: true })).toBeVisible()
  await expect(row(idle.title)).toBeVisible()
  expect((await readerRow(stack, working.id)).attention.working).toBe(true)
  await stack.acp.release("activity-cycle")
})
