export const PUBLIC_API_ERRORS = {
  repository_provider_unauthorized: { status: 502, message: "Repository provider refused authorization" },
  repository_provider_unavailable: { status: 502, message: "Repository provider is unavailable" },
  host_tunnel_timeout: { status: 503, retryable: true, message: "Host tunnel timed out" },
  host_tunnel_response_body_too_large: { status: 413, message: "Host tunnel response body exceeds the relay limit" },
  host_tunnel_unavailable: { status: 503, retryable: true, message: "Host tunnel is unavailable" },
  workspace_checkpoint_unavailable: { status: 503, retryable: true, message: "Workspace checkpoint is unavailable" },
  workspace_checkpoint_conflict: { status: 409, message: "Workspace checkpoint conflicted" },
  invalid_input: { family: "access", status: 400, message: "The request names an invalid value" },
  organization_policy_denied: { family: "access", status: 403, message: "Organization creation is disabled for this deployment" },
  org_admin_required: { family: "access", status: 403, message: "Organization administrator authority is required" },
  org_owner_required: { family: "access", status: 403, message: "Only an organization owner may grant, change or remove the owner role" },
  org_owner_protected: { family: "access", status: 409, message: "The organization's founding owner cannot be removed or demoted" },
  team_member_org_membership_required: { family: "access", status: 403, message: "The team member must belong to the team organization" },
  project_member_org_membership_required: { family: "access", status: 403, message: "The project member must belong to the project organization" },
  org_membership_required: { family: "access", status: 403, message: "Organization membership is required" },
  project_admin_required: { family: "access", status: 403, message: "Project administrator authority is required" },
  team_not_allowed_on_personal_org: { family: "access", status: 400, message: "Personal organizations cannot contain teams" },
  team_member_target_required: { family: "access", status: 400, message: "Exactly one team member target is required" },
  org_member_target_required: { family: "access", status: 400, message: "Exactly one organization member target is required" },
  org_member_email_unsupported: { family: "access", status: 400, message: "This deployment cannot find accounts by email" },
  organization_not_found: { family: "access", status: 404, message: "Organization not found" },
  team_not_found: { family: "access", status: 404, message: "Team not found" },
  team_member_not_found: { family: "access", status: 404, message: "Team member not found" },
  org_member_not_found: { family: "access", status: 404, message: "Organization member not found" },
  project_not_found: { family: "access", status: 404, message: "Project not found" },
  project_member_not_found: { family: "access", status: 404, message: "Project member not found" },
  project_member_owner_immutable: { family: "access", status: 409, message: "The project owner's access cannot be changed" },
  resource_conflict: { family: "access", status: 409, message: "Organization or team authority changed concurrently" },
  session_not_found: { family: "session_share", status: 404, message: "This session is not on the control plane, so it cannot be shared from People yet." },
  session_share_admin_required: { family: "session_share", status: 403, message: "Only the person who started this session can manage its People." },
  session_share_target_required: { family: "session_share", status: 400, message: "Exactly one share target is required" },
  session_share_target_not_found: { family: "session_share", status: 404, message: "Share target was not found" },
  session_share_target_outside_organization: { family: "session_share", status: 403, message: "That person is not in this organization, so this session cannot be shared with them." },
  session_share_level_invalid: { family: "session_share", status: 400, message: "A share level is either follow or send." },
  session_share_team_org_mismatch: { family: "session_share", status: 400, message: "The team must belong to the session workspace organization." },
  session_share_org_mismatch: { family: "session_share", status: 400, message: "The organization must own the session workspace." },
  workspace_backing_conflict: { status: 409, message: "Workspace is provisioned in the cloud and cannot be placed on a machine" },
  invalid_session_list_cursor: { status: 400, message: "Session list cursor does not match this query" },
  BAD_REQUEST: { status: 400, message: "Invalid request" },
  INTERNAL_SERVER_ERROR: { status: 500, message: "Internal error" },
  CONTROL_PLANE_UNAVAILABLE: { status: 503, message: "Control Plane services are not configured" },
  credential_verification_unsupported: { status: 400, message: "Credential provider does not support verification" },
  credential_shape_invalid: { status: 400, message: "Credential secret has an unsupported shape" },
  credential_provider_unavailable: { status: 502, retryable: true, message: "Credential provider request failed" },
  credential_verification_failed: { status: 502, message: "Credential provider verification failed" },
  credential_redirect_denied: { status: 502, message: "Sandbox provider redirects are not allowed" },
  credential_endpoint_invalid: { status: 400, message: "Invalid credential provider endpoint" },
  host_attestation_denied: { status: 403, message: "host_attestation_denied" },
  signature_replayed: { status: 409, message: "signature_replayed" },
  host_enrollment_not_found: { status: 404, message: "host_enrollment_not_found" },
  enrollment_revoked: { status: 403, message: "enrollment_revoked" },
  enrollment_paused: { status: 403, message: "enrollment_paused" },
  enrollment_owner_ineligible: { status: 403, message: "enrollment_owner_ineligible" },
  enrollment_key_version_mismatch: { status: 403, message: "enrollment_key_version_mismatch" },
  invitation_invalid: { status: 403, message: "invitation_invalid" },
  invitation_expired: { status: 410, message: "invitation_expired" },
  invitation_revoked: { status: 410, message: "invitation_revoked" },
  invitation_redeemed: { status: 409, message: "invitation_redeemed" },
  invitation_host_conflict: { status: 409, message: "invitation_host_conflict" },
  enrollment_generation_superseded: { status: 409, message: "enrollment_generation_superseded" },
  host_assignment_outside_scope: { status: 400, message: "host_assignment_outside_scope" },
  host_sealing_key_undeclared: { status: 409, message: "host_sealing_key_undeclared" },
  host_provider_config_revision_stale: { status: 409, message: "host_provider_config_revision_stale" },
  identity_conflict: { status: 409, message: "identity_conflict" },
  registration_transition_denied: { status: 403, message: "registration_transition_denied" },
  actor_authorization_denied: { status: 403, message: "actor_authorization_denied" },
} as const

export type PublicApiErrorCode = keyof typeof PUBLIC_API_ERRORS
