export type DocumentsServiceEnv = Readonly<{
  DOCUMENTS_DB: D1Database
  DOCUMENTS_BUCKET: R2Bucket
  CLAXEDO_DOCUMENTS_ENVIRONMENT_ID: string
  CLAXEDO_DOCUMENTS_DEPLOYMENT_ID: string
  CLAXEDO_DOCUMENTS_SERVICE_BUILD_ID: string
  CLAXEDO_DOCUMENTS_BINDING_PROVENANCE: string
  CLAXEDO_DOCUMENTS_INITIAL_STATE: "installed_disabled"
}>
