import { fileURLToPath } from "node:url"
import { acpScriptToken, expect, SCRIPTED_ACP_HARNESS, test } from "../harness"

const IMAGE = fileURLToPath(new URL("../../public/web-app-manifest-192x192.png", import.meta.url))
const IMAGE_NAME = "web-app-manifest-192x192.png"

test("06 composer: a marked image, an @file pill and a slash command popover all reach the sent prompt", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("composer")
  await stack.acp.write("ack", { steps: [{ kind: "text", text: "Received the attachments" }] })
  const session = await api.createSession(workspace.directory, { title: "Composer", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}/w/${workspace.id}/s/${session.id}`)
  const prompt = app.getByRole("textbox", { name: "Ask anything, / for commands, @ for context..." })

  await prompt.click()
  await app.keyboard.type("/")
  await expect(app.getByRole("listbox", { name: "Commands" })).toBeVisible()
  await app.keyboard.press("Escape")
  await expect(app.getByRole("listbox", { name: "Commands" })).toHaveCount(0)
  await app.keyboard.press("Backspace")

  const chooser = app.waitForEvent("filechooser")
  await app.getByRole("button", { name: "Add", exact: true }).click()
  await app.getByRole("menuitem", { name: /Images and files/ }).click()
  await (await chooser).setFiles(IMAGE)
  await app.getByRole("button", { name: "Mark up image" }).click()
  const dialog = app.getByRole("dialog", { name: "Mark up image" })
  const picture = await dialog.getByRole("img", { name: IMAGE_NAME }).boundingBox()
  if (!picture) throw new Error("The image to mark has no box")
  await app.mouse.move(picture.x + picture.width * 0.2, picture.y + picture.height * 0.2)
  await app.mouse.down()
  await app.mouse.move(picture.x + picture.width * 0.6, picture.y + picture.height * 0.6, { steps: 6 })
  await app.mouse.up()
  const comment = dialog.getByRole("textbox")
  await comment.fill("the logo corner")
  await comment.press("Enter")
  await dialog.getByRole("button", { name: "Save", exact: true }).click()
  await expect(dialog).toHaveCount(0)

  await prompt.click()
  await app.keyboard.type("Look at @READ")
  await app.getByRole("option", { name: "README.md" }).click()
  await app.keyboard.type(` ${acpScriptToken("ack")}`)
  await app.keyboard.press("Enter")

  await expect(app.getByText("Received the attachments")).toBeVisible()
  const messages = await api.messages(workspace.directory, session.id)
  const sent = JSON.stringify(messages.find((message) => message.info.role === "user")?.parts ?? [])
  expect(sent).toContain("image/png")
  expect(sent).toContain("README.md")
  expect(sent).toContain("the logo corner")
})

test("06 a new session starts on the folder's harness, then on the harness last used for a draft in the workspace", async ({ stack, api, app, isMobile }) => {
  const workspace = await stack.daemon.makeWorkspace("defaults")
  const existing = await api.createSession(workspace.directory, { title: "Existing", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}/w/${workspace.id}/s/${existing.id}`)
  await expect(app.getByRole("textbox", { name: "Ask anything, / for commands, @ for context..." })).toBeVisible()
  const openDraft = async () => {
    if (isMobile) await app.getByRole("button", { name: "Open menu" }).click()
    await app.getByRole("button", { name: "New session" }).click()
    return app.getByRole("region", { name: "New session", exact: true })
  }

  const draft = await openDraft()
  const picker = draft.locator('[data-action="prompt-harness-model"]')
  await expect(picker).toHaveAttribute("data-harness", "pi")
  await picker.click()
  await app.getByRole("button", { name: /^Harness/ }).click()
  await app.getByRole("button", { name: "Scripted ACP" }).click()
  await expect(picker).toHaveAttribute("data-harness", "scripted-acp")
  await app.keyboard.press("Escape")
  const prompt = draft.getByRole("textbox", { name: "Ask anything, / for commands, @ for context..." })
  await prompt.fill("Start on the scripted agent")
  await prompt.press("Enter")
  await expect(draft).toHaveCount(0)
  const created = (await api.sessions(workspace.directory)).find((row) => row.id !== existing.id)
  expect(JSON.stringify(created)).toContain('"harness":{"id":"scripted-acp","access":"connection"}')

  await app.reload()
  await expect(app.getByRole("textbox", { name: "Ask anything, / for commands, @ for context..." }).first()).toBeVisible()
  const next = await openDraft()
  await expect(next.locator('[data-action="prompt-harness-model"]')).toHaveAttribute("data-harness", "scripted-acp")
})

test("06 a draft and the prompt history survive a reload, and a shell command is sent as plain text", async ({ stack, api, app }) => {
  const workspace = await stack.daemon.makeWorkspace("persist")
  await stack.acp.write("persist", { steps: [{ kind: "text", text: "Noted" }] })
  const session = await api.createSession(workspace.directory, { title: "Persist", harness: SCRIPTED_ACP_HARNESS })
  await app.goto(`${stack.url}/w/${workspace.id}/s/${session.id}`)
  const prompt = app.getByRole("textbox", { name: "Ask anything, / for commands, @ for context..." })
  await prompt.fill(`Remember this prompt ${acpScriptToken("persist")}`)
  await prompt.press("Enter")
  await expect(app.getByText("Noted")).toBeVisible()
  await prompt.fill("A draft that outlives a reload")
  await app.reload()
  await expect(prompt).toHaveText("A draft that outlives a reload")
  await prompt.fill("")
  await prompt.press("ArrowUp")
  await expect(prompt).toContainText("Remember this prompt")

  await prompt.fill("")
  await prompt.press("!")
  const shell = app.getByRole("textbox", { name: /^Enter shell command/ })
  await expect(shell).toBeVisible()
  await shell.pressSequentially("echo shell-text")
  await shell.press("Enter")
  await expect(prompt).toBeVisible()
  await expect.poll(async () => JSON.stringify(await api.messages(workspace.directory, session.id))).toContain('"text":"echo shell-text"')
})
