import type { IconProps as OpenCodeIconProps } from "@opencode-ai/ui/icon"
import type { AppIconName } from "@/ui/icons/catalog"
import { defineIconLibrary } from "@/ui/icons/registry"

type OpenCodeGlyphName = OpenCodeIconProps["name"]

const OPEN_CODE_GLYPHS = [
  "align-right",
  "arrow-up",
  "arrow-left",
  "arrow-right",
  "archive",
  "bubble-5",
  "prompt",
  "brain",
  "fork",
  "maximize",
  "marketplace",
  "workgraph",
  "bullet-list",
  "check-small",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-grabber-vertical",
  "chevron-double-right",
  "circle-x",
  "close",
  "close-small",
  "checklist",
  "console",
  "terminal",
  "terminal-square",
  "terminal-active",
  "review",
  "review-active",
  "expand",
  "collapse",
  "code",
  "code-lines",
  "circle-ban-sign",
  "edit-small-2",
  "eye",
  "enter",
  "folder",
  "file-tree",
  "file-tree-active",
  "magnifying-glass",
  "plus-small",
  "plus",
  "new-session",
  "new-session-active",
  "pencil-line",
  "mcp",
  "glasses",
  "magnifying-glass-menu",
  "window-cursor",
  "task",
  "subagent",
  "stop",
  "status",
  "status-active",
  "sidebar",
  "sidebar-active",
  "layout-left",
  "layout-left-partial",
  "layout-left-full",
  "layout-right",
  "layout-right-partial",
  "layout-right-full",
  "square-arrow-top-right",
  "open-file",
  "speech-bubble",
  "comment",
  "folder-add-left",
  "github",
  "discord",
  "layout-bottom",
  "layout-bottom-partial",
  "layout-bottom-full",
  "dot-grid",
  "circle-check",
  "circle-alert",
  "circle-dashed",
  "circle-half",
  "chevron-double-left",
  "file",
  "copy",
  "check",
  "photo",
  "share",
  "shield",
  "download",
  "menu",
  "server",
  "branch",
  "edit",
  "help",
  "settings-gear",
  "dash",
  "cloud-upload",
  "trash",
  "sliders",
  "keyboard",
  "selector",
  "arrow-down-to-line",
  "warning",
  "reset",
  "link",
  "providers",
  "models",
  "arrow-undo-down",
] as const satisfies readonly OpenCodeGlyphName[]

const OPEN_CODE_ALIASES = {
  changes: "code-lines",
  circle: "circle-dashed",
  claude: "models",
  cloud: "cloud-upload",
  "collapse-all": "collapse",
  cursor: "window-cursor",
  edit: "edit-small-2",
  "expand-all": "expand",
  "file-text": "file",
  filetree: "file-tree",
  "folder-open": "folder",
  folders: "folder",
  gauge: "status",
  globe: "server",
  "grid-plus": "folder-add-left",
  kebab: "dot-grid",
  hand: "shield",
  laptop: "terminal",
  magnifying: "magnifying-glass",
  monitor: "terminal",
  "more-horizontal": "dot-grid",
  openai: "models",
  opencode: "models",
  "outline-chevron-down": "chevron-down",
  "outline-copy": "copy",
  "outline-dots": "dot-grid",
  "outline-reset": "reset",
  "outline-share": "share",
  "outline-sliders": "sliders",
  "outline-square-arrow": "square-arrow-top-right",
  "outline-xmark": "close-small",
  page: "file",
  "page-plus": "folder-add-left",
  pencil: "pencil-line",
  pin: "status",
  "pin-filled": "status-active",
  pi: "terminal",
  play: "enter",
  process: "subagent",
  "process-command": "console",
  "process-cwd": "folder",
  "process-name": "subagent",
  reload: "reset",
  "scroll-to-latest": "arrow-down-to-line",
  send: "arrow-up",
  settings: "settings-gear",
  "sidebar-right": "layout-right",
  speech: "speech-bubble",
  split: "layout-right-partial",
  unified: "layout-right-full",
  workspace: "maximize",
  "workspace-isolated": "maximize",
  "workspace-new": "folder-add-left",
  worktree: "branch",
  "xmark-small": "close-small",
} as const satisfies Partial<Record<AppIconName, OpenCodeGlyphName>>

export const openCodeIconLibrary = defineIconLibrary<AppIconName, OpenCodeGlyphName>({
  name: "opencode",
  glyphs: OPEN_CODE_GLYPHS,
  aliases: OPEN_CODE_ALIASES,
})
