// Theme-independent choices are selected by resolveIconArtworkLibrary before these family mappings.
import { PROCESS_ICON_GLYPHS } from "@opencode-ai/ui/process-icon-map"

import type { IconProps as OpenCodeIconProps } from "@opencode-ai/ui/icon"
import type { AppIconName } from "@/ui/icons/catalog"
import { defineIconLibrary } from "@/ui/icons/registry"

type OpenCodeGlyphName = OpenCodeIconProps["name"]

const OPEN_CODE_GLYPHS = [
  "folders",
  "pi",
  "opencode",
  "openai",
  "cursor",
  "claude",
  // Accepted as-is for now (user review, 2026-09-09).
  "monitor",
  "unified",
  "split",
  "collapse-all",
  "expand-all",
  "document-text",
  "align-right",
  "arrow-up",
  "arrow-left",
  "arrow-right",
  "archive",
  "bubble-5",
  "prompt",
  "brain",
  "fork",
  "maximize",
  "marketplace",
  "check-small",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  // Accepted as-is for now (user review, 2026-09-09).
  "chevron-double-right",
  "circle-x",
  "close",
  "close-small",
  "checklist",
  "terminal",
  "terminal-active",
  "review",
  // Accepted as-is for now (user review, 2026-09-09).
  "review-active",
  "expand",
  "collapse",
  "code",
  // Accepted as-is for now (user review, 2026-09-09).
  "code-lines",
  // Accepted as-is for now (user review, 2026-09-09).
  "circle-ban-sign",
  "edit",
  "eye",
  "enter",
  "folder",
  "magnifying-glass",
  "plus-small",
  "plus",
  "new-session",
  // Accepted as-is for now (user review, 2026-09-09).
  "new-session-active",
  "pencil-line",
  "mcp",
  "glasses",
  "magnifying-glass-menu",
  "window-cursor",
  "subagent",
  "stop",
  "status",
  "status-active",
  "sidebar",
  "sidebar-active",
  "layout-left",
  "layout-left-partial",
  "layout-left-full",
  // Accepted as-is for now (user review, 2026-09-09).
  "layout-right-partial",
  // Accepted as-is for now (user review, 2026-09-09).
  "layout-right-full",
  "open-external",
  "open-file",
  "page-plus",
  "speech-bubble",
  "comment",
  "folder-add",
  "github",
  "discord",
  "layout-bottom",
  "three-dots",
  "circle-check",
  "circle-alert",
  "circle-dashed",
  "circle-half",
  // Accepted as-is for now (user review, 2026-09-09).
  "chevron-double-left",
  "file",
  "copy",
  "check",
  "photo",
  "share",
  "shield",
  "download",
  // Accepted as-is for now (user review, 2026-09-09).
  "server",
  "branch",
  "edit",
  "help",
  "settings-gear",
  "dash",
  "cloud-upload",
  "trash",
  "sliders",
  "keyboard",
  // Accepted as-is for now (user review, 2026-09-09).
  "arrow-down-to-line",
  "warning",
  "reset",
  "link",
  "providers",
  "models",
  "arrow-undo-down",
] as const satisfies readonly OpenCodeGlyphName[]

const OPEN_CODE_ALIASES = {
  ...PROCESS_ICON_GLYPHS.opencode,
  "changes": "review",
  "inspect-element": "window-cursor",
  cloud: "cloud-upload",
  "folder-open": "folders",
  gauge: "status",
  globe: "server",
  magnifying: "magnifying-glass",
  "outline-chevron-down": "chevron-down",
  "outline-copy": "copy",
  "outline-share": "share",
  "outline-sliders": "sliders",
  "outline-xmark": "close-small",
  page: "file",
  pencil: "pencil-line",
  reload: "reset",
  "scroll-to-latest": "arrow-down-to-line",
  task: "checklist",
  send: "arrow-up",
  settings: "settings-gear",
  speech: "speech-bubble",
  "workspace-new": "folder-add",
  worktree: "branch",
  "xmark-small": "close-small",
} as const satisfies Partial<Record<AppIconName, OpenCodeGlyphName>>

export const openCodeIconLibrary = defineIconLibrary<AppIconName, OpenCodeGlyphName>({
  name: "opencode",
  glyphs: OPEN_CODE_GLYPHS,
  aliases: OPEN_CODE_ALIASES,
})
