export type { Edge, KeyMap, MovePaneTarget, Pane, PaneRect, Snapshot, SplitNode, SplitPath, SplitTree, WorkbenchState } from "./types"
export { NEW_PANE } from "./types"
export type { OpenedPane, PaneContent, WorkbenchApi, WorkbenchRecord, WorkbenchStore } from "./store"
export { createWorkbenchStore } from "./store"
export { WorkbenchProvider, useWorkbench } from "./provider"
export type { PaneContext } from "./pane-context"
export { usePaneContext } from "./pane-context"
export type { DragController, DragSourceKind, DropZone } from "./drag/pointer-drag"
export type { DragSourceOptions } from "./drag/drag-source"
export { useDragSource } from "./drag/drag-source"
export { Workbench } from "./view/workbench"
export type { WorkbenchProps } from "./view/workbench"
export { WorkbenchTabs } from "./view/tabs"
export { WorkbenchPaneSwitcher } from "./view/pane-switcher"
export { dictionary as workbenchDictionary } from "./i18n"
