export type { AddProjectFlow, ProjectCreated } from "./add-project"
export { createAddProjectFlow, useAddProjectFlow } from "./add-project"
export type { ProjectsKey, ProjectsText } from "./i18n"
export { dictionary as projectsDictionary, useProjectsText } from "./i18n"
export type { AddProjectEvent, AddProjectState, AddProjectStep, PlacementChoice, ProjectDraft } from "./model"
export { addProjectStep, addProjectSteps, addProjectTransition, draftProjectName, sourceLabel } from "./model"
export { useCreatedProjectOpener, usePlacementOpener } from "./open"
export { projectSettingsPath } from "./routes"
export { AVATAR_COLOR_KEYS } from "./project-colors"
export type { ProjectList, RailProject } from "./project-list"
export { createProjectList, ProjectListProvider, useProjectList } from "./project-list"
export type { Loaded, ProjectView } from "./store"
export { useMachines, useProject, useProjectCommands, useProjectPlacements, useProjects } from "./store"
export { AddProjectSteps } from "./view/add-project-steps"
export { placementKindLabel, PlacementList } from "./view/placement-list"
export { DialogEditProject } from "./view/edit-project-dialog"
export { NewSessionContextRow, type DraftTarget } from "./view/new-session-context-row"
export { ProjectCreateForm, type ProjectCreateFormProps } from "./view/project-create-form"
export { projectsSettingsSection } from "./view/projects-settings"
