import type { PiModelCatalogProvider } from "./harnesses/pi/catalog"

export type { PiModelCatalogProvider, PiModelCatalogModel } from "./harnesses/pi/catalog"

/** Data-only entry generated by scripts/build.ts from the canonical Pi registry. */
export declare function piModelCatalog(): PiModelCatalogProvider[]
