/**
 * The operations a renderer may ask Electron main to run, by name.
 *
 * Import-free on purpose: this is the contract a reviewer reads on its own. A
 * caller naming an absent operation fails to compile, and the tables that
 * satisfy every member (this package's registry and Electron main's routes)
 * cannot quietly gain a request-shaped passthrough.
 */
export type HostedOperationName =
  | "account.mode"
  | "account.compatibility"
  | "account.cliExchange"
  | "account.agentSettings.read"
  | "account.agentSettings.write"
  | "agentPlugins.catalog"
  | "agentPlugins.catalog.refresh"
  | "agentPlugins.catalog.project"
  | "agentPlugins.catalog.project.refresh"
  | "agentPlugins.activation"
  | "agentPlugins.organizationDefault"
  | "agentPlugins.update"
  | "agentPlugins.skill"
  | "agentPlugins.runtimeSelf"
  | "agentPlugins.skill.project"
  | "agentPlugins.sources.list"
  | "agentPlugins.sources.add"
  | "agentPlugins.sources.remove"
  | "connections.list"
  | "connections.connect"
  | "connections.attempt"
  | "connections.disconnect"
  // One per host the list route names, because it answers rows only under a
  // named host and the host-less call is always empty.
  | "workspace.list.provisioner"
  | "workspace.list.machine"
  | "workspace.resolve"
  | "workspace.create"
  | "workspace.lifecycle"
  | "workspace.checkpoints.list"
  | "workspace.checkpoints.create"
  | "workspace.checkpoints.restore"
  | "workspace.connection.mint"
  | "workspace.connection.refresh"
  | "host.enrollCurrentMachine"
  | "host.enrollmentNonce"
  | "host.renameCurrentMachine"
  | "workspace.assignHost"
  | "workspace.unassignHost"
  | "session.list"
  | "session.page"
  | "session.projection.register"
  | "session.projection.checkpoint"
  | "session.projection.repair"
  | "controlPlane.events"
  | "session.shares.list"
  | "session.shares.grant"
  | "session.shares.revoke"
  | "session.participants.add"
  | "org.list"
  | "org.create"
  | "org.teams.list"
  | "org.teams.create"
  | "org.ensureDefaultTeam"
  | "org.members.list"
  | "org.invitations.create"
  | "org.invitations.list"
  | "org.invitations.revoke"
  | "org.invitations.accept"
  | "org.members.update"
  | "org.members.remove"
  | "team.members.list"
  | "team.members.add"
  | "team.members.remove"
  | "team.projects.list"
  | "team.projects.grant"
  | "team.projects.revoke"
  | "project.members.grant"
  | "project.members.revoke"
  | "project.access"
  | "connections.repositories"
  | "connections.reverify"
  | "documents.list"
  | "documents.get"
  | "documents.create"
  | "documents.update"
  | "documents.content.get"
  | "documents.content.put"
  | "documents.snapshots"
  | "documents.snapshots.restore"
  | "documents.workSource"
  | "documents.workSourcePin"
  | "documents.statuses"
  | "documents.export"
  | "documents.agentOpen"
  | "documents.runtimeConflictResolve"
  | "documents.moveToRepository"
  | "documents.fromRepo"
  | "session.create"
  | "session.messages"
  | "session.outline"
  | "session.turnPage"
  | "session.part"
  | "session.gateway"
  | "usage.cloudFacts"
  | "plugin.request"

export type RunHostedOperation = (operation: HostedOperationName, input?: Readonly<Record<string, unknown>>) => Promise<unknown>
