#!/usr/bin/env bun
/**
 * Pre-build script for Claxedo Electron desktop app.
 *
 * Rebuilds the installable CLI and embedded engine, bundles server components,
 * copies ACP binaries, and copies channel-specific icons —
 * so that `bun run build` + `bun run package:mac` produces
 * a fully up-to-date app.
 */

import { $ } from "bun"
import * as fs from "fs"
import { createRequire } from "node:module"
import * as path from "path"

import { bundleClaxedoEngineWorker, bundleClaxedoServer } from "./bundle-claxedo-server"
import {
  buildClaxedoServerCompileCache,
  buildOpenCodeCompileCache,
  resolveElectronBinary,
} from "./build-opencode-compile-cache"
import {
  CLAXEDO_SERVER_COMPILE_CACHE_DIR_NAME,
  OPENCODE_COMPILE_CACHE_DIR_NAME,
} from "../src/shared/opencode-compile-cache"
import { bundleHostConnector } from "./bundle-host-connector"
import { buildMemoryImpactHelper } from "./build-memory-impact-helper"
import { LOCAL_SERVER_ENTRY, resolveLocalServerEntry } from "./local-server"
import { prepareRichContentRenderer } from "./build-rich-content-renderer"
import { copyIcons as copyChannelIcons } from "./utils"

// ── Paths ──

const SCRIPT_DIR = import.meta.dir
const PACKAGE_DIR = path.resolve(SCRIPT_DIR, "..")
const AGENT_RUNTIME_DIR = path.resolve(PACKAGE_DIR, "../agent-sdk-runtime")
const OPENCODE_DIR = path.resolve(PACKAGE_DIR, "../opencode")
const WS_RUNTIME_DIR = path.resolve(PACKAGE_DIR, "../workspace-runtime")
const RESOURCES_DIR = path.resolve(PACKAGE_DIR, "resources")
const ACP_DIR = path.resolve(RESOURCES_DIR, "acp")

const log = (msg: string) => console.log(`[prebuild] ${msg}`)

// ── Icons ──

async function copyIcons() {
  const copied = copyChannelIcons()
  log(`Copied ${copied.channel} icons`)
}

// ── claxedo-server ──

async function bundleServer() {
  // The BOOT stub, not the product entry: it seeds the compile cache and then
  // reaches `claxedo-server-entry.ts` through a dynamic import, so the 9.11 MB
  // closure behind it is compiled after the cache is live. See
  // scripts/claxedo-server-boot.ts.
  const src = path.resolve(SCRIPT_DIR, "claxedo-server-boot.ts")
  const dest = path.resolve(RESOURCES_DIR, "claxedo-server")

  if (!fs.existsSync(src)) {
    throw new Error(`claxedo-server source not found at ${src}`)
  }
  // Resolve the declared local-server entry BEFORE the expensive builds. Bun
  // would report a missing dependency as a bundler log buried under a
  // multi-minute engine build; this fails in the first second and names the
  // package the desktop cannot start without.
  log(`Local server entry: ${LOCAL_SERVER_ENTRY} → ${resolveLocalServerEntry(PACKAGE_DIR)}`)
  // workspace-runtime imports agent-sdk-runtime through its published `dist`
  // exports. Build that authoritative input first: otherwise a package can
  // contain yesterday's adapter even though today's source and tests are green.
  log("Building agent-sdk-runtime...")
  await $`bun run build`.cwd(AGENT_RUNTIME_DIR)
  log("Building workspace-runtime...")
  await $`bun run build`.cwd(WS_RUNTIME_DIR)
  log("Building SDK-next embedded OpenCode...")
  await $`bun run build:node`.cwd(OPENCODE_DIR)
  log("Bundling claxedo-server...")
  const bundled = await bundleClaxedoServer(src, dest)
  log(`claxedo-server bundled to ${bundled.entry} (${Math.ceil(bundled.outputBytes / 1024 / 1024)} MB split)`)
  await bundleClaxedoEngineWorker(
    path.resolve(SCRIPT_DIR, "claxedo-engine-worker-entry.ts"),
    path.resolve(RESOURCES_DIR, "claxedo-engine-worker"),
  )
  log("claxedo engine worker bundled")

  // Strictly after `build:node`: the cache is generated by importing the engine
  // artifact that was just built, with the same Electron binary and the same V8
  // flags the server child runs. Regenerating on every build is what keeps the
  // cache's source hash matching the artifact — a stale cache is not a wrong
  // answer, V8 rejects it, but it is a silently lost 155 ms.
  log("Generating the OpenCode V8 compile cache...")
  const compileCache = await buildOpenCodeCompileCache({
    enginePath: path.resolve(OPENCODE_DIR, "dist/node/node.js"),
    outputDir: path.resolve(RESOURCES_DIR, OPENCODE_COMPILE_CACHE_DIR_NAME),
    electronPath: resolveElectronBinary(PACKAGE_DIR),
    log: (message) => log(`compile cache: ${message}`),
  })
  for (const entry of compileCache.manifest.entries) {
    log(`compile cache: ${entry.file} (${entry.type}, ${entry.bytes} bytes)`)
  }

  // Strictly after the server bundle exists, and generated from the DEFERRED
  // chunk the boot stub imports — entering at index.js would hit the same
  // startup refusal before the dynamic import and cache nothing.
  log("Generating the claxedo-server V8 compile cache...")
  const serverCache = await buildClaxedoServerCompileCache({
    deferredEntryPath: bundled.deferredEntry,
    bundleDir: dest,
    outputDir: path.resolve(RESOURCES_DIR, CLAXEDO_SERVER_COMPILE_CACHE_DIR_NAME),
    electronPath: resolveElectronBinary(PACKAGE_DIR),
    log: (message) => log(`server compile cache: ${message}`),
  })
  const serverCacheBytes = serverCache.manifest.entries.reduce((total, entry) => total + entry.bytes, 0)
  log(`server compile cache: ${serverCache.manifest.entries.length} entr(ies), ${serverCacheBytes} bytes`)
}

// ── ACP binaries ──

async function bundleClaudeAgentAcp() {
  const desktopPkg = await Bun.file(path.resolve(PACKAGE_DIR, "package.json")).json()
  const version = desktopPkg.devDependencies?.["@agentclientprotocol/claude-agent-acp"]
  if (!version) throw new Error("claxedo-desktop is missing @agentclientprotocol/claude-agent-acp")
  const require = createRequire(path.resolve(PACKAGE_DIR, "package.json"))
  const packagePath = require.resolve("@agentclientprotocol/claude-agent-acp/package.json")
  const installed = await Bun.file(packagePath).json()
  if (installed.version !== version) {
    throw new Error(`claude-agent-acp version mismatch: expected ${version}, found ${installed.version}`)
  }
  const entry = path.resolve(path.dirname(packagePath), "dist/index.js")
  if (!fs.existsSync(entry)) throw new Error(`claude-agent-acp entry not found at ${entry}`)

  const dest = path.resolve(ACP_DIR, "claude-agent-acp")
  const tmpDir = path.resolve(ACP_DIR, ".claude-acp-tmp")

  log("Bundling claude-agent-acp...")
  await $`bun build ${entry} --outdir ${tmpDir} --target=node --minify`
  let bundled = fs.readFileSync(path.join(tmpDir, "index.js"), "utf-8")
  bundled = bundled.replace(/^#!.*\n/, "")
  fs.writeFileSync(
    dest,
    `#!/usr/bin/env node
if (Number.parseInt(process.versions.node, 10) < 22) {
  console.error("Claude ACP requires Node.js 22 or newer. Install Node 22+ and restart Claxedo.")
  process.exit(1)
}
${bundled}`,
  )
  fs.chmodSync(dest, 0o755)
  fs.rmSync(tmpDir, { recursive: true, force: true })
  log("claude-agent-acp bundled")
}

async function bundleCodexAcp() {
  const dest = path.resolve(ACP_DIR, "codex-acp")
  const tmpDir = path.resolve(ACP_DIR, ".codex-acp-tmp")

  fs.rmSync(dest, { force: true })
  fs.rmSync(`${dest}.exe`, { force: true })
  fs.rmSync(path.resolve(ACP_DIR, "codex-vendor"), { recursive: true, force: true })

  // Plain bundled JS like claude-agent-acp — Node 22+ auto-detects the ESM
  // syntax in the extensionless file. No runtime ships inside the app: the
  // adapter runs on the user's Node and spawns the user's system `codex`.
  log("Bundling codex-acp...")
  await $`bun build ${path.resolve(SCRIPT_DIR, "codex-acp-entry.ts")} --outdir ${tmpDir} --target=node --minify`
  let bundled = fs.readFileSync(path.join(tmpDir, "codex-acp-entry.js"), "utf-8")
  bundled = bundled.replace(/^#!.*\n/, "")
  fs.writeFileSync(
    dest,
    `#!/usr/bin/env node
if (Number.parseInt(process.versions.node, 10) < 22) {
  console.error("Codex ACP requires Node.js 22 or newer. Install Node 22+ and restart Claxedo.")
  process.exit(1)
}
${bundled}`,
  )
  fs.chmodSync(dest, 0o755)
  fs.rmSync(tmpDir, { recursive: true, force: true })
  log("codex-acp bundled")
}

async function copyAcpBinaries() {
  fs.mkdirSync(ACP_DIR, { recursive: true })
  await bundleClaudeAgentAcp()
  await bundleCodexAcp()
}

// ── Main ──

// Optional children, native helpers, and the server are independent build outputs.
await Promise.all([
  copyIcons(),
  copyAcpBinaries(),
  bundleServer(),
  bundleHostConnector(),
  buildMemoryImpactHelper(),
  prepareRichContentRenderer({ required: process.env.CLAXEDO_REQUIRE_NATIVE_RICH_CONTENT === "1" }),
])

log("Done.")
