export const EVENT_TYPES = {
  RUN_CREATED: "run_created",
  RUN_PLANNED: "run_planned",
  TEAM_CREATED: "team_created",
  TEAM_STATUS_CHANGED: "team_status_changed",
  TEAM_MEMBER_ADDED: "team_member_added",
  NODE_CREATED: "node_created",
  NODE_STATUS_CHANGED: "node_status_changed",
  EDGE_ADDED: "edge_added",
  EDGE_REMOVED: "edge_removed",
  GATE_SATISFIED: "gate_satisfied",
  GATE_REOPENED: "gate_reopened",
  MESSAGE_POSTED: "message_posted",
  HANDOFF_REQUESTED: "handoff_requested",
  HANDOFF_ACCEPTED: "handoff_accepted",
  HANDOFF_REJECTED: "handoff_rejected",
  QUESTION_ASKED: "question_asked",
  QUESTION_ANSWERED: "question_answered",
  LEAD_PLAN_CREATED: "lead_plan_created",
  LEAD_GAP_DETECTED: "lead_gap_detected",
  LEAD_REROUTE_REQUESTED: "lead_reroute_requested",
  REACTION_TRIGGERED: "reaction_triggered",
  WATCHDOG_ESCALATED: "watchdog_escalated",
  FEATURE_SLICE_HYDRATED: "feature_slice_hydrated",
  ISSUE_HYDRATED: "issue_hydrated",
  ISSUE_UPDATED: "issue_updated",
  ISSUE_LINKED: "issue_linked",
  ISSUE_COMMENT_ADDED: "issue_comment_added",
  QUESTION_SCOPED: "question_scoped",
  ROUTE_SCORED: "route_scored",
  ROUTE_SELECTED: "route_selected",
  DISPATCH_REQUESTED: "dispatch_requested",
  SCRATCHPAD_WRITTEN: "scratchpad_written",
  SCRATCHPAD_PROMOTED: "scratchpad_promoted",
  ARTIFACT_CREATED: "artifact_created",
  DECISION_PROPOSED: "decision_proposed",
  DECISION_CHALLENGED: "decision_challenged",
  DECISION_ACCEPTED: "decision_accepted",
  DECISION_REJECTED: "decision_rejected",
  SYNC_PUSH_ACKED: "sync_push_acked",
  SYNC_PULL_APPLIED: "sync_pull_applied",
  CONFLICT_DETECTED: "conflict_detected",
  CONFLICT_RESOLVED: "conflict_resolved",
  SNAPSHOT_CREATED: "snapshot_created",
  REPAIR_REBUILD_COMPLETED: "repair_rebuild_completed",
} as const;

export type EventType = typeof EVENT_TYPES[keyof typeof EVENT_TYPES];
