import type { PlacementId, ProjectId } from "./ids"
import type { DiffScope, FileSearchEntries } from "./git-types"

export const queryKeys = {
  sharedSessions: (server: string) => ["server", server, "shared-sessions"] as const,
  bootstrap: (server: string) => ["server", server, "bootstrap"] as const,
  accountCatalog: (server: string) => ["server", server, "account-catalog"] as const,
  projects: (server: string) => ["server", server, "projects"] as const,
  project: (server: string, id: ProjectId) => ["server", server, "projects", id] as const,
  placements: (server: string) => ["server", server, "placements"] as const,
  placementsOf: (server: string, projectId: ProjectId) => ["server", server, "placements", projectId] as const,
  machines: (server: string) => ["server", server, "machines"] as const,
  accounts: (server: string) => ["server", server, "accounts"] as const,
  accountsEffective: (server: string) => ["server", server, "accounts", "effective"] as const,
  machineLogins: (server: string) => ["server", server, "accounts", "machine-logins"] as const,
  accountSources: (server: string) => ["server", server, "accounts", "sources"] as const,
  usage: (server: string, request: unknown) => ["server", server, "usage", request] as const,
  usageAll: (server: string) => ["server", server, "usage"] as const,
  marketplace: (server: string, projectId: ProjectId | undefined) => ["server", server, "marketplace", projectId ?? ""] as const,
  marketplaceAll: (server: string) => ["server", server, "marketplace"] as const,
  marketplaceSources: (server: string) => ["server", server, "plugin-sources"] as const,
  marketplaceSkill: (server: string, request: { readonly pluginInstanceId: string; readonly skill: string; readonly projectId?: string }) =>
    ["server", server, "plugin-skill", request.pluginInstanceId, request.skill, request.projectId ?? ""] as const,
  marketplaceMachine: (server: string) => ["server", server, "plugin-machine-installed"] as const,
  livePlugins: (server: string) => ["server", server, "live-plugins"] as const,
  tasks: (server: string) => ["server", server, "tasks", "availability"] as const,
  tasksAll: (server: string) => ["server", server, "tasks"] as const,
  cloud: (server: string) => ["server", server, "cloud"] as const,
  folderPaths: (server: string) => ["server", server, "folders", "paths"] as const,
  folderChildren: (server: string, directory: string) => ["server", server, "folders", "children", directory] as const,
  harnessOptions: (server: string, placementId: PlacementId, harness: string) => ["server", server, "harness", placementId, harness] as const,
  harnessCommands: (server: string, placementId: PlacementId, harness: string) => ["server", server, "harness-commands", placementId, harness] as const,
  stopsBackgroundTasks: (server: string, placementId: PlacementId, sessionId: string) => ["server", server, "stops-background-tasks", placementId, sessionId] as const,
  codeHostAll: (server: string) => ["server", server, "codeHost"] as const,
  integrations: (server: string) => ["server", server, "integrations"] as const,
  agentConnections: (server: string) => ["server", server, "agent-connections"] as const,
  providerAuth: (server: string, harness: string) => ["server", server, "providerAuth", harness] as const,
  providerCatalogs: (server: string) => ["server", server, "providerCatalog"] as const,
  providerCatalog: (server: string, harness: string, placementId: PlacementId | undefined) =>
    ["server", server, "providerCatalog", harness, placementId ?? ""] as const,
  codeHostRepositories: (server: string, connectionId: string) => ["server", server, "codeHost", "repositories", connectionId] as const,
  fileTree: (server: string, placementId: PlacementId, path: string) => ["server", server, "files", placementId, "tree", path] as const,
  localFilesAll: () => ["desktop", "files"] as const,
  localFileContent: (placementId: PlacementId, path: string) => ["desktop", "files", placementId, "content", path] as const,
  fileContent: (server: string, placementId: PlacementId, path: string) => ["server", server, "files", placementId, "content", path] as const,
  fileSearch: (server: string, placementId: PlacementId, query: string, entries: FileSearchEntries) => ["server", server, "files", placementId, "search", entries, query] as const,
  filesAll: (server: string) => ["server", server, "files"] as const,
  filesOf: (server: string, placementId: PlacementId) => ["server", server, "files", placementId] as const,
  gitStatus: (server: string, placementId: PlacementId) => ["server", server, "git", placementId, "status"] as const,
  gitLog: (server: string, placementId: PlacementId, limit: number) => ["server", server, "git", placementId, "log", limit] as const,
  gitRefs: (server: string, placementId: PlacementId) => ["server", server, "git", placementId, "refs"] as const,
  gitBases: (server: string, placementId: PlacementId) => ["server", server, "git", placementId, "bases"] as const,
  gitDiff: (server: string, placementId: PlacementId, scope: DiffScope) => ["server", server, "git", placementId, "diff", scope] as const,
  gitDiffFile: (server: string, placementId: PlacementId, scope: DiffScope, file: string) => ["server", server, "git", placementId, "diff", scope, file] as const,
  gitAll: (server: string) => ["server", server, "git"] as const,
  gitOf: (server: string, placementId: PlacementId) => ["server", server, "git", placementId] as const,
} as const
