import type { Component, JSX } from "solid-js"
import { Match, Switch } from "solid-js"

// Sandbox driver brand marks.
//
// These are inlined rather than pulled from `@opencode-ai/ui/provider-icon`:
// that sprite is GENERATED by the icon-spritesheet generator and covers model
// providers, so hand-adding sandbox drivers there would be overwritten on the
// next regen. It also has no mark for daytona/modal/box/exe.
//
// Sources: Vercel, Cloudflare, Docker, Box and Modal marks are from
// simple-icons (CC0-1.0, https://github.com/simple-icons/simple-icons). The
// Daytona mark is the logomark from https://www.daytona.io/brand, normalised to
// its own bounding box. Every mark is monochrome and inherits `currentColor`,
// so the tiles stay legible in both themes and never fight the surface tokens.
// Brand marks remain trademarks of their owners and are used here only to
// identify each service in the picker.
//
// exe.dev publishes no mark, so it falls back to a monogram — see `Monogram`.

type LogoProps = { class?: string }

function svg(props: LogoProps & { viewBox: string; children: JSX.Element }) {
  return (
    <svg
      viewBox={props.viewBox}
      fill="currentColor"
      aria-hidden="true"
      class={props.class}
    >
      {props.children}
    </svg>
  )
}

const Vercel: Component<LogoProps> = (props) =>
  svg({ ...props, viewBox: "0 0 24 24", children: <path d="m12 1.608 12 20.784H0Z" /> })

const Cloudflare: Component<LogoProps> = (props) =>
  svg({ ...props, viewBox: "0 0 24 24", children: <path d="M16.5088 16.8447c.1475-.5068.0908-.9707-.1553-1.3154-.2246-.3164-.6045-.499-1.0615-.5205l-8.6592-.1123a.1559.1559 0 0 1-.1333-.0713c-.0283-.042-.0351-.0986-.021-.1553.0278-.084.1123-.1484.2036-.1562l8.7359-.1123c1.0351-.0489 2.1601-.8868 2.5537-1.9136l.499-1.3013c.0215-.0561.0293-.1128.0147-.168-.5625-2.5463-2.835-4.4453-5.5499-4.4453-2.5039 0-4.6284 1.6177-5.3876 3.8614-.4927-.3658-1.1187-.5625-1.794-.499-1.2026.119-2.1665 1.083-2.2861 2.2856-.0283.31-.0069.6128.0635.894C1.5683 13.171 0 14.7754 0 16.752c0 .1748.0142.3515.0352.5273.0141.083.0844.1475.1689.1475h15.9814c.0909 0 .1758-.0645.2032-.1553l.12-.4268zm2.7568-5.5634c-.0771 0-.1611 0-.2383.0112-.0566 0-.1054.0415-.127.0976l-.3378 1.1744c-.1475.5068-.0918.9707.1543 1.3164.2256.3164.6055.498 1.0625.5195l1.8437.1133c.0557 0 .1055.0263.1329.0703.0283.043.0351.1074.0214.1562-.0283.084-.1132.1485-.204.1553l-1.921.1123c-1.041.0488-2.1582.8867-2.5527 1.914l-.1406.3585c-.0283.0713.0215.1416.0986.1416h6.5977c.0771 0 .1474-.0489.169-.126.1122-.4082.1757-.837.1757-1.2803 0-2.6025-2.125-4.727-4.7344-4.727" /> })

const Docker: Component<LogoProps> = (props) =>
  svg({ ...props, viewBox: "0 0 24 24", children: <path d="M13.983 11.078h2.119a.186.186 0 00.186-.185V9.006a.186.186 0 00-.186-.186h-2.119a.185.185 0 00-.185.185v1.888c0 .102.083.185.185.185m-2.954-5.43h2.118a.186.186 0 00.186-.186V3.574a.186.186 0 00-.186-.185h-2.118a.185.185 0 00-.185.185v1.888c0 .102.082.185.185.185m0 2.716h2.118a.187.187 0 00.186-.186V6.29a.186.186 0 00-.186-.185h-2.118a.185.185 0 00-.185.185v1.887c0 .102.082.185.185.186m-2.93 0h2.12a.186.186 0 00.184-.186V6.29a.185.185 0 00-.185-.185H8.1a.185.185 0 00-.185.185v1.887c0 .102.083.185.185.186m-2.964 0h2.119a.186.186 0 00.185-.186V6.29a.185.185 0 00-.185-.185H5.136a.186.186 0 00-.186.185v1.887c0 .102.084.185.186.186m5.893 2.715h2.118a.186.186 0 00.186-.185V9.006a.186.186 0 00-.186-.186h-2.118a.185.185 0 00-.185.185v1.888c0 .102.082.185.185.185m-2.93 0h2.12a.185.185 0 00.184-.185V9.006a.185.185 0 00-.184-.186h-2.12a.185.185 0 00-.184.185v1.888c0 .102.083.185.185.185m-2.964 0h2.119a.185.185 0 00.185-.185V9.006a.185.185 0 00-.184-.186h-2.12a.186.186 0 00-.186.186v1.887c0 .102.084.185.186.185m-2.92 0h2.12a.185.185 0 00.184-.185V9.006a.185.185 0 00-.184-.186h-2.12a.185.185 0 00-.184.185v1.888c0 .102.082.185.185.185M23.763 9.89c-.065-.051-.672-.51-1.954-.51-.338.001-.676.03-1.01.087-.248-1.7-1.653-2.53-1.716-2.566l-.344-.199-.226.327c-.284.438-.49.922-.612 1.43-.23.97-.09 1.882.403 2.661-.595.332-1.55.413-1.744.42H.751a.751.751 0 00-.75.748 11.376 11.376 0 00.692 4.062c.545 1.428 1.355 2.48 2.41 3.124 1.18.723 3.1 1.137 5.275 1.137.983.003 1.963-.086 2.93-.266a12.248 12.248 0 003.823-1.389c.98-.567 1.86-1.288 2.61-2.136 1.252-1.418 1.998-2.997 2.553-4.4h.221c1.372 0 2.215-.549 2.68-1.009.309-.293.55-.65.707-1.046l.098-.288Z" /> })

const Box: Component<LogoProps> = (props) =>
  svg({ ...props, viewBox: "0 0 24 24", children: <path d="M.959 5.523c-.54 0-.959.42-.959.899v7.549a4.59 4.59 0 004.613 4.494 4.717 4.717 0 004.135-2.457c.779 1.438 2.337 2.457 4.074 2.457 2.577 0 4.674-2.037 4.674-4.613.06-2.457-2.037-4.495-4.613-4.495-1.738 0-3.295.959-4.074 2.397-.78-1.438-2.338-2.397-4.135-2.397-1.079 0-2.038.36-2.817.899V6.422a.92.92 0 00-.898-.899zM17.602 9.26a.95.95 0 00-.704.158c-.36.3-.479.899-.18 1.318l2.397 3.116-2.396 3.115c-.3.42-.24.96.18 1.26.419.3 1.016.298 1.316-.122l2.039-2.636 2.096 2.697c.3.36.899.419 1.318.12.36-.3.42-.84.121-1.259l-2.338-3.115 2.338-3.057c.3-.419.298-1.018-.121-1.318-.48-.3-1.019-.24-1.318.18l-2.096 2.576-2.04-2.695c-.149-.18-.373-.3-.612-.338zM4.613 11.154c1.558 0 2.817 1.26 2.817 2.758 0 1.558-1.259 2.756-2.817 2.756-1.558 0-2.816-1.198-2.816-2.756 0-1.498 1.258-2.758 2.816-2.758zm8.27 0c1.558 0 2.816 1.26 2.816 2.758-.06 1.558-1.318 2.756-2.816 2.756-1.558 0-2.817-1.198-2.817-2.756 0-1.498 1.259-2.758 2.817-2.758Z" /> })

const Modal: Component<LogoProps> = (props) =>
  svg({ ...props, viewBox: "0 0 24 24", children: <path d="M4.89 5.57 0 14.002l2.521 4.4h5.05l4.396-7.718 4.512 7.709 4.996.037L24 14.057l-4.857-8.452-5.073-.015-2.076 3.598L9.94 5.57Zm.837.729h3.787l1.845 3.252H7.572Zm9.189.021 3.803.012 4.228 7.355-3.736-.027zm-9.82.346L6.94 9.914l-4.209 7.389-1.892-3.3Zm9.187.014 4.297 7.343-1.892 3.282-4.3-7.344zm-6.713 3.6h3.79l-4.212 7.394H3.361Zm11.64 4.109 3.74.027-1.893 3.281-3.74-.027z" /> })

// The published asset is a 454x320 brand tile; this viewBox crops to the
// logomark's own bounding box so it optically matches the 24x24 marks above.
const Daytona: Component<LogoProps> = (props) =>
  svg({
    ...props,
    viewBox: "94 130 50.93 53.07",
    children: (
      <>
        <path d="m126.103 130-15.679 15.678v-6.703h-6.335v15.31h6.335v-8.607l4.48 4.48 15.678-15.679zm-4.592 13.726h21.117v6.335h-21.117zM96.7 165.899h9.244L94 153.955l4.48-4.48 12.041 12.041-4.383 4.383h9.04v6.335H96.701zm16.967 17.172 12.597-12.597v9.679h6.335v-19.006h-6.335v9.136l-4.384-4.384-12.692 12.692z" />
        <path d="m126.263 154.541 14.185 14.185 4.48-4.479-14.185-14.186z" />
      </>
    ),
  })

/** Fallback for drivers with no published mark (currently exe.dev). */
const Monogram: Component<LogoProps & { label: string }> = (props) => (
  <span
    aria-hidden="true"
    class={`grid place-items-center rounded-[5px] border border-border-base text-11-medium ${props.class ?? ""}`}
  >
    {props.label.slice(0, 1).toUpperCase()}
  </span>
)

export const SandboxDriverLogo: Component<{ id: string; label: string; class?: string }> = (props) => (
  <Switch fallback={<Monogram label={props.label} class={props.class} />}>
    <Match when={props.id === "vercel"}>
      <Vercel class={props.class} />
    </Match>
    <Match when={props.id === "cloudflare"}>
      <Cloudflare class={props.class} />
    </Match>
    <Match when={props.id === "docker"}>
      <Docker class={props.class} />
    </Match>
    <Match when={props.id === "box"}>
      <Box class={props.class} />
    </Match>
    <Match when={props.id === "modal"}>
      <Modal class={props.class} />
    </Match>
    <Match when={props.id === "daytona"}>
      <Daytona class={props.class} />
    </Match>
  </Switch>
)
