import { describe, expect, test } from "bun:test"
import { createHash } from "node:crypto"
import {
  buildAuthorizeUrl,
  createPkcePair,
  createState,
  loopbackRedirectUri,
  readCallback,
  statesMatch,
} from "./pkce"

const REDIRECT_PATH = "/claxedo/auth/callback"

function pair() {
  return createPkcePair()
}

describe("createPkcePair", () => {
  test("challenge is the S256 hash of the verifier", () => {
    // The whole mechanism. If the challenge were anything else, the token
    // exchange would fail — or, worse, succeed while proving nothing.
    const { verifier, challenge, method } = pair()

    expect(method).toBe("S256")
    expect(challenge).toBe(createHash("sha256").update(verifier).digest("base64url"))
  })

  test("verifier is unreserved characters within the RFC 7636 length range", () => {
    const { verifier } = pair()

    expect(verifier.length).toBeGreaterThanOrEqual(43)
    expect(verifier.length).toBeLessThanOrEqual(128)
    expect(verifier).toMatch(/^[A-Za-z0-9\-._~]+$/)
  })

  test("is different on every call", () => {
    // A reused verifier would let a stolen code from an earlier attempt be
    // exchanged during a later one.
    expect(pair().verifier).not.toBe(pair().verifier)
  })

  test("draws from the injected randomness, so it is the entropy source under test", () => {
    // Positive control for the two assertions above: they must be reading
    // generated bytes, not a constant that happens to look right.
    const fixed = createPkcePair(() => Buffer.alloc(32, 7))
    expect(fixed.verifier).toBe(Buffer.alloc(32, 7).toString("base64url"))
    expect(fixed.challenge).toBe(createHash("sha256").update(fixed.verifier).digest("base64url"))
  })
})

describe("buildAuthorizeUrl", () => {
  const request = {
    authorizeUrl: "https://accounts.example.com/oauth/authorize",
    clientId: "client_desktop",
    redirectUri: loopbackRedirectUri(49_152, REDIRECT_PATH),
    scope: "openid profile email",
    pkce: pair(),
    state: createState(),
  }

  test("carries the challenge and never the verifier", () => {
    // The authorize URL is handed to the system browser and lands in history,
    // logs and the address bar. A verifier there would defeat PKCE entirely.
    const url = new URL(buildAuthorizeUrl(request))

    expect(url.searchParams.get("code_challenge")).toBe(request.pkce.challenge)
    expect(url.searchParams.get("code_challenge_method")).toBe("S256")
    expect(buildAuthorizeUrl(request)).not.toContain(request.pkce.verifier)
  })

  test("requests a code, with the state and loopback redirect", () => {
    const url = new URL(buildAuthorizeUrl(request))

    expect(url.searchParams.get("response_type")).toBe("code")
    expect(url.searchParams.get("client_id")).toBe("client_desktop")
    expect(url.searchParams.get("state")).toBe(request.state)
    expect(url.searchParams.get("redirect_uri")).toBe(`http://127.0.0.1:49152${REDIRECT_PATH}`)
  })

  test("preserves query the authorization server already requires", () => {
    // Clerk and others put the instance in the authorize URL itself. Rebuilding
    // the URL from parts would silently drop it.
    const url = new URL(buildAuthorizeUrl({ ...request, authorizeUrl: `${request.authorizeUrl}?instance=abc` }))

    expect(url.searchParams.get("instance")).toBe("abc")
    expect(url.searchParams.get("response_type")).toBe("code")
  })
})

describe("loopbackRedirectUri", () => {
  test("uses the literal loopback address, not the localhost name", () => {
    // RFC 8252 §7.3: a name can be redirected by a hosts entry or a resolver;
    // the literal address cannot.
    expect(loopbackRedirectUri(1234, REDIRECT_PATH)).toBe(`http://127.0.0.1:1234${REDIRECT_PATH}`)
    expect(loopbackRedirectUri(1234, REDIRECT_PATH)).not.toContain("localhost")
  })
})

describe("readCallback", () => {
  const expectedState = createState()
  const ok = (query: string) => readCallback({ url: `${REDIRECT_PATH}${query}`, expectedState, redirectPath: REDIRECT_PATH })

  test("returns the code when path and state match", () => {
    expect(ok(`?code=abc&state=${expectedState}`)).toEqual({ ok: true, code: "abc" })
  })

  test("rejects a mismatched state", () => {
    // Without this, any process that can reach the loopback listener can hand
    // it a code of its own and sign the user into an attacker's account.
    const result = ok("?code=abc&state=someone-elses")

    expect(result.ok).toBe(false)
    expect(result.ok === false && result.reason).toContain("state did not match")
  })

  test("rejects a callback with no state at all", () => {
    // Distinct from a mismatch: an absent state is a client that never sent
    // one, which would otherwise read as "nothing to compare, so fine".
    expect(ok("?code=abc").ok).toBe(false)
  })

  test("rejects a callback with no code", () => {
    expect(ok(`?state=${expectedState}`).ok).toBe(false)
  })

  test("reports the authorization server's own error", () => {
    const result = ok(`?error=access_denied&state=${expectedState}`)

    expect(result.ok).toBe(false)
    expect(result.ok === false && result.reason).toContain("access_denied")
  })

  test("rejects a request to any other path on the listener", () => {
    // The listener answers one path. A favicon request, or a probe from
    // another process, must not be read as a callback.
    const result = readCallback({ url: `/other?code=abc&state=${expectedState}`, expectedState, redirectPath: REDIRECT_PATH })

    expect(result.ok).toBe(false)
    expect(result.ok === false && result.reason).toContain("unexpected callback path")
  })
})

describe("statesMatch", () => {
  test("accepts equal states and rejects unequal ones", () => {
    expect(statesMatch("abc", "abc")).toBe(true)
    expect(statesMatch("abc", "abd")).toBe(false)
  })

  test("rejects a prefix rather than throwing on the length difference", () => {
    // `timingSafeEqual` throws on unequal lengths; an unguarded call would turn
    // a hostile callback into an unhandled exception instead of a rejection.
    expect(statesMatch("abcdef", "abc")).toBe(false)
    expect(statesMatch("abc", "")).toBe(false)
  })
})
