import "./ui/styles.css"
import "./shell/styles/index.css"
import "./shell/styles/ui-overrides.css"
import "@opencode-ai/ui/v2/menu-v2.css"
import "@opencode-ai/ui/v2/tooltip-v2.css"
import "./shell/styles/app-shell.css"
import "./transcript/styles.css"
